
import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.Random;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * bookingticket.java
 *
 * Created on May 17, 2017, 10:46:38 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class bookingticket extends javax.swing.JFrame {

    /** Creates new form bookingticket */
    public bookingticket() {
        initComponents();
        String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Random rnd= new Random();
StringBuilder sb = new StringBuilder(8);
for (int i=0;i<8;i++)
{sb.append(contain.charAt(rnd.nextInt(contain.length())));}
String random =sb.toString();
Cap_LB.setText(random);
        
        Uid_LB.setVisible(false);
        RB3.setSelected(true);
         getContentPane().setBackground(new Color(51,0,204));

         

         Sex_CB5.setEnabled(false);Sex_CB1.setEnabled(false);jComboBox4.setEnabled(false);Sex_CB2.setEnabled(false); Sex_CB3.setEnabled(false); Sex_CB4.setEnabled(false);Ctz_CB4.setEnabled(false);Ctz_CB1.setEnabled(false); Ctz_CB2.setEnabled(false); Ctz_CB3.setEnabled(false); Ctz_CB5.setEnabled(false); Id_CB5.setEnabled(false);Id_CB1.setEnabled(false); Id_CB2.setEnabled(false); Id_CB3.setEnabled(false);

   Id_CB4.setEnabled(false);Sex_CB5.setVisible(false);Sex_CB1.setVisible(false);jComboBox4.setVisible(false);Sex_CB2.setVisible(false); Sex_CB3.setVisible(false); Sex_CB4.setVisible(false);Ctz_CB4.setVisible(false);Ctz_CB1.setVisible(false);Ctz_CB2.setVisible(false);Ctz_CB3.setVisible(false); Ctz_CB5.setVisible(false); Id_CB5.setVisible(false); Id_CB1.setVisible(false); Id_CB2.setVisible(false); Id_CB3.setVisible(false);

    Id_CB4.setVisible(false); Name_TF1.setEnabled(false);Name_TF2.setEnabled(false);Name_TF3.setEnabled(false);Name_TF4.setEnabled(false);Name_TF5.setEnabled(false);Age_TF5.setEnabled(false);Age_TF1.setEnabled(false);Age_TF2.setEnabled(false);Age_TF3.setEnabled(false);Age_TF4.setEnabled(false);

     Name_TF1.setVisible(false);Name_TF2.setVisible(false);Name_TF3.setVisible(false);Name_TF4.setVisible(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);Age_TF1.setVisible(false);Age_TF2.setVisible(false);Age_TF3.setVisible(false);Age_TF4.setVisible(false);
    
     Sr_LB1.setEnabled(false);Sr_LB2.setEnabled(false);Sr_LB3.setEnabled(false);Sr_LB5.setEnabled(false);Sr_LB4.setEnabled(false);
     Sr_LB1.setVisible(false);Sr_LB2.setVisible(false);Sr_LB3.setVisible(false);Sr_LB5.setVisible(false);Sr_LB4.setVisible(false);


    
     sex_CB2.setEnabled(false);sex_CB1.setEnabled(false);sex_CB2.setVisible(false);sex_CB1.setVisible(false);
     CAge_TF1.setEnabled(false);Cname_TF2.setEnabled(false);CAge_TF2.setEnabled(false);Cname_TF1.setEnabled(false);
     CAge_TF1.setVisible(false);Cname_TF2.setVisible(false);CAge_TF2.setVisible(false);Cname_TF1.setVisible(false);
     S_LB1.setEnabled(false);S_LB1.setVisible(false);S_LB2.setEnabled(false);S_LB2.setVisible(false);
     Sex_CB.setEnabled(false);Ctz_CB.setEnabled(false);Id_CB.setEnabled(false);Sex_CB.setVisible(false);Ctz_CB.setVisible(false);Id_CB.setVisible(false);
Sr_LB.setEnabled(false);Sr_LB.setVisible(false);
Age_TF.setEnabled(false);Name_TF.setEnabled(false);Age_TF.setVisible(false);Name_TF.setVisible(false);
sex_CB.setEnabled(false);sex_CB.setVisible(false);
S_LB.setEnabled(false);S_LB.setVisible(false);
Cname_TF.setEnabled(false);CAge_TF.setEnabled(false);Cname_TF.setVisible(false);CAge_TF.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Avail_TF = new javax.swing.JTextField();
        Trname_TF = new javax.swing.JTextField();
        Class_TF = new javax.swing.JTextField();
        Trno_TF = new javax.swing.JTextField();
        Quota_TF = new javax.swing.JTextField();
        Type_TF = new javax.swing.JTextField();
        Dist_TF = new javax.swing.JTextField();
        Upto_TF = new javax.swing.JTextField();
        To_TF = new javax.swing.JTextField();
        From_TF = new javax.swing.JTextField();
        BP_TF = new javax.swing.JTextField();
        Date_TF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        sex_lb = new javax.swing.JLabel();
        sno_lb = new javax.swing.JLabel();
        name_lb = new javax.swing.JLabel();
        age_lb = new javax.swing.JLabel();
        S_LB2 = new javax.swing.JLabel();
        S_LB = new javax.swing.JLabel();
        S_LB1 = new javax.swing.JLabel();
        Cname_TF2 = new javax.swing.JTextField();
        CAge_TF2 = new javax.swing.JTextField();
        Cname_TF1 = new javax.swing.JTextField();
        Cname_TF = new javax.swing.JTextField();
        CAge_TF = new javax.swing.JTextField();
        CAge_TF1 = new javax.swing.JTextField();
        sex_CB2 = new javax.swing.JComboBox();
        sex_CB = new javax.swing.JComboBox();
        sex_CB1 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Sr_LB1 = new javax.swing.JLabel();
        Sr_LB5 = new javax.swing.JLabel();
        Sr_LB = new javax.swing.JLabel();
        Sr_LB2 = new javax.swing.JLabel();
        Sr_LB3 = new javax.swing.JLabel();
        Sr_LB4 = new javax.swing.JLabel();
        Name_TF = new javax.swing.JTextField();
        Name_TF1 = new javax.swing.JTextField();
        Name_TF2 = new javax.swing.JTextField();
        Name_TF3 = new javax.swing.JTextField();
        Name_TF4 = new javax.swing.JTextField();
        Name_TF5 = new javax.swing.JTextField();
        Sex_CB5 = new javax.swing.JComboBox();
        Sex_CB = new javax.swing.JComboBox();
        Sex_CB1 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        Sex_CB2 = new javax.swing.JComboBox();
        Sex_CB3 = new javax.swing.JComboBox();
        Sex_CB4 = new javax.swing.JComboBox();
        Ctz_CB4 = new javax.swing.JComboBox();
        Ctz_CB = new javax.swing.JComboBox();
        Ctz_CB1 = new javax.swing.JComboBox();
        Ctz_CB2 = new javax.swing.JComboBox();
        Ctz_CB3 = new javax.swing.JComboBox();
        Ctz_CB5 = new javax.swing.JComboBox();
        Id_CB5 = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        Id_CB = new javax.swing.JComboBox();
        Id_CB1 = new javax.swing.JComboBox();
        Id_CB2 = new javax.swing.JComboBox();
        Id_CB3 = new javax.swing.JComboBox();
        Id_CB4 = new javax.swing.JComboBox();
        Age_TF1 = new javax.swing.JTextField();
        Age_TF2 = new javax.swing.JTextField();
        Age_TF3 = new javax.swing.JTextField();
        Age_TF4 = new javax.swing.JTextField();
        Age_TF5 = new javax.swing.JTextField();
        Age_TF = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        cb2 = new javax.swing.JCheckBox();
        RB_2 = new javax.swing.JRadioButton();
        RB_1 = new javax.swing.JRadioButton();
        cb1 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        RB3 = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        Cap_TF = new javax.swing.JTextField();
        Cap_LB = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        Mob_TF = new javax.swing.JTextField();
        captcha_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        replan_btn = new javax.swing.JButton();
        next_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        Nop_Cb = new javax.swing.JComboBox();
        Uid_LB = new javax.swing.JLabel();
        nocp_cb = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Ticket Reservation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Train Name:-");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setText("Class:-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel7.setText("Date:-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel8.setText("Date:-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel10.setText("From:-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel12.setText("To:-");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel14.setText("Train No:-");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel16.setText("Boarding Point:-");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel18.setText("Reservation Upto:-");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel21.setText("Quota:-");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel22.setText("Availbility:-");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel24.setText("Distance:-");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel26.setText("Type:-");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        Avail_TF.setEditable(false);
        jPanel2.add(Avail_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, -1));

        Trname_TF.setEditable(false);
        jPanel2.add(Trname_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        Class_TF.setEditable(false);
        jPanel2.add(Class_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 90, -1));

        Trno_TF.setEditable(false);
        jPanel2.add(Trno_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 90, -1));

        Quota_TF.setEditable(false);
        jPanel2.add(Quota_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));

        Type_TF.setEditable(false);
        jPanel2.add(Type_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 90, -1));

        Dist_TF.setEditable(false);
        jPanel2.add(Dist_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, -1));

        Upto_TF.setEditable(false);
        Upto_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upto_TFActionPerformed(evt);
            }
        });
        jPanel2.add(Upto_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, -1));

        To_TF.setEditable(false);
        jPanel2.add(To_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, -1));

        From_TF.setEditable(false);
        jPanel2.add(From_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        BP_TF.setEditable(false);
        jPanel2.add(BP_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        Date_TF.setEditable(false);
        jPanel2.add(Date_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 700, 260));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sex_lb.setText("SEX");
        jPanel5.add(sex_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        sno_lb.setText("S NO");
        jPanel5.add(sno_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        name_lb.setText("NAME");
        jPanel5.add(name_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        age_lb.setText("AGE");
        jPanel5.add(age_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        S_LB2.setText("3");
        jPanel5.add(S_LB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 10, -1));

        S_LB.setText("1");
        jPanel5.add(S_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        S_LB1.setText("2");
        jPanel5.add(S_LB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 10, -1));
        jPanel5.add(Cname_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 120, -1));
        jPanel5.add(CAge_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 70, -1));
        jPanel5.add(Cname_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, -1));
        jPanel5.add(Cname_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, -1));
        jPanel5.add(CAge_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 70, -1));
        jPanel5.add(CAge_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 70, -1));

        sex_CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel5.add(sex_CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, -1));

        sex_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel5.add(sex_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, -1, -1));

        sex_CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel5.add(sex_CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 750, 560, 160));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("S NO.");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel9.setText("Name");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jLabel11.setText("Age");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        jLabel13.setText("Sex");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, 10));

        jLabel15.setText("Senior Citizen");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        jLabel17.setText("Id Card Type");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 30, -1, -1));

        Sr_LB1.setText("2.");
        jPanel3.add(Sr_LB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        Sr_LB5.setText("6.");
        jPanel3.add(Sr_LB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        Sr_LB.setText("1.");
        jPanel3.add(Sr_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        Sr_LB2.setText("3.");
        jPanel3.add(Sr_LB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        Sr_LB3.setText("4.");
        jPanel3.add(Sr_LB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        Sr_LB4.setText("5.");
        jPanel3.add(Sr_LB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, 10));

        Name_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TFActionPerformed(evt);
            }
        });
        jPanel3.add(Name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 130, -1));

        Name_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_TF1ActionPerformed(evt);
            }
        });
        jPanel3.add(Name_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 130, -1));
        jPanel3.add(Name_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));
        jPanel3.add(Name_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 130, -1));
        jPanel3.add(Name_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 130, -1));
        jPanel3.add(Name_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 130, -1));

        Sex_CB5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel3.add(Sex_CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        Sex_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        Sex_CB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sex_CBActionPerformed(evt);
            }
        });
        jPanel3.add(Sex_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        Sex_CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel3.add(Sex_CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel3.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        Sex_CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel3.add(Sex_CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        Sex_CB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        jPanel3.add(Sex_CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        Sex_CB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "Male", "Female", "Transgender" }));
        Sex_CB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sex_CB4ActionPerformed(evt);
            }
        });
        jPanel3.add(Sex_CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        Ctz_CB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        Ctz_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, -1, -1));

        Ctz_CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, -1, -1));

        Ctz_CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, -1, -1));

        Ctz_CB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        Ctz_CB5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Senior Citizen?", "Yes", "No" }));
        jPanel3.add(Ctz_CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        Id_CB5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        jPanel3.add(Id_CB5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, -1, -1));

        jLabel28.setForeground(new java.awt.Color(255, 0, 0));
        jLabel28.setText("To Be Present During Journey");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        Id_CB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        jPanel3.add(Id_CB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        Id_CB1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        Id_CB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_CB1ActionPerformed(evt);
            }
        });
        jPanel3.add(Id_CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 100, -1, -1));

        Id_CB2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        Id_CB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Id_CB2ActionPerformed(evt);
            }
        });
        jPanel3.add(Id_CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, -1, -1));

        Id_CB3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        jPanel3.add(Id_CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        Id_CB4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select ID", "Aadhar Card", "Pan Card", "Driving Licence" }));
        jPanel3.add(Id_CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));
        jPanel3.add(Age_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 60, -1));
        jPanel3.add(Age_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 60, -1));
        jPanel3.add(Age_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 60, -1));
        jPanel3.add(Age_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 60, -1));
        jPanel3.add(Age_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 60, -1));
        jPanel3.add(Age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 60, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 860, 270));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cb2.setText("Consider Auto Upgradation. ");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        jPanel4.add(cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        buttonGroup1.add(RB_2);
        RB_2.setText("Book my ticket if all the passengers are alloted berths in same coach.");
        RB_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RB_2ActionPerformed(evt);
            }
        });
        jPanel4.add(RB_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        buttonGroup1.add(RB_1);
        RB_1.setText("None");
        jPanel4.add(RB_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        cb1.setText("Book only if confirm berths are allotted");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        jPanel4.add(cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 940, 370, 140));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel36.setForeground(new java.awt.Color(255, 51, 51));
        jLabel36.setText("If you need assured Lower Berths or assured compact accommodation (in same coach), please select one of the options");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel37.setForeground(new java.awt.Color(255, 51, 51));
        jLabel37.setText("If 'None' is selected, the berths will be allotted based on the system logic, depending on availability at that point of time");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel39.setForeground(new java.awt.Color(255, 51, 51));
        jLabel39.setText("Berth preference does not guarantee allotment of preferred berth type.");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jLabel40.setForeground(new java.awt.Color(255, 51, 51));
        jLabel40.setText("This choice shall not be applicable in case confirmed accommodation is not available in the train");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel41.setForeground(new java.awt.Color(255, 51, 51));
        jLabel41.setText("Booking shall be done in PRS in the coach given by the user if seats are available, otherwise the passenger is allotted in any other coach.");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 940, 710, 140));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Travel Insurance", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setText("Do you want to take Travel Insurance (Rs 0 / person)?");
        jPanel7.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        RB3.setText("Yes And I Accept the Terms & Conditions of the Travel Insurance Policy.");
        jPanel7.add(RB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1120, 1050, 60));

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Captcha and other details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setForeground(new java.awt.Color(255, 51, 51));
        jLabel43.setText("IRCTC has introduced Image based captcha for enhanced security and better user ");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, -1));

        jLabel44.setForeground(new java.awt.Color(255, 51, 51));
        jLabel44.setText("experience on passenger detail page. Please read the question carefully in image captcha");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, -1, -1));

        jLabel45.setForeground(new java.awt.Color(255, 51, 51));
        jLabel45.setText("and answer accordingly to proceed further.");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, -1, -1));

        jLabel38.setText("Mobile Number : +91");
        jPanel8.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));
        jPanel8.add(Cap_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 140, 20));

        Cap_LB.setFont(new java.awt.Font("Times New Roman", 3, 18));
        Cap_LB.setText("HDWD585M");
        jPanel8.add(Cap_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 40));

        jLabel48.setText("Enter captcha:-");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));
        jPanel8.add(Mob_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 30, 140, 20));

        captcha_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ref.jpg"))); // NOI18N
        captcha_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captcha_btnActionPerformed(evt);
            }
        });
        jPanel8.add(captcha_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, 20, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recaptcha.jpg"))); // NOI18N
        jPanel8.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 90));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 1200, 1050, 140));

        jLabel49.setForeground(new java.awt.Color(255, 51, 51));
        jLabel49.setText("* If for any reason, the reservation output details are not displayed on your screen after you have made payments,please check the details in 'Booked Tickets' under ");
        jPanel1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1390, -1, -1));

        jLabel50.setForeground(new java.awt.Color(255, 51, 51));
        jLabel50.setText("book your ticket again.");
        jPanel1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1430, -1, -1));

        jLabel51.setForeground(new java.awt.Color(255, 51, 51));
        jLabel51.setText("'Booking History' in left navigation bar. You may also check your mail for the details of your booking. You are also advised to contact Indian Railways before trying to ");
        jPanel1.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1410, -1, -1));

        jLabel52.setForeground(new java.awt.Color(255, 51, 51));
        jLabel52.setText("** The ID card will be required during journey. One of the passenger booked on an e-ticket should have any of the nine identity cards(Voter Photo Identity Card /");
        jPanel1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 1470, -1, -1));

        jLabel53.setForeground(new java.awt.Color(255, 51, 51));
        jLabel53.setText("Passport / PAN Card / Driving License issued by a RTO/ Photo Identity card issued by Central / State Govt / Student Photo Identity Card issued by recognized School or ");
        jPanel1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1490, -1, -1));

        jLabel54.setForeground(new java.awt.Color(255, 51, 51));
        jLabel54.setText("College for their students/ Nationalized Bank Passbook with photograph/Credits Cards issued by banks with laminated photograph / Unique Identification Card 'Aadhaar')");
        jPanel1.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1510, -1, -1));

        jLabel55.setForeground(new java.awt.Color(255, 51, 51));
        jLabel55.setText("during train journey in original.The identification details are required at the time of Tatkal booking.**");
        jPanel1.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 1530, -1, -1));

        replan_btn.setText("Replan");
        replan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replan_btnActionPerformed(evt);
            }
        });
        jPanel1.add(replan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 1360, -1, -1));

        next_btn.setText("Next");
        next_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                next_btnActionPerformed(evt);
            }
        });
        jPanel1.add(next_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1360, -1, -1));

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 1360, -1, -1));

        Nop_Cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Of Passengers", "1", "2", "3", "4", "5", "6" }));
        Nop_Cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Nop_CbActionPerformed(evt);
            }
        });
        jPanel1.add(Nop_Cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        Uid_LB.setText("jLabel19");
        jPanel1.add(Uid_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 1400, -1, -1));

        nocp_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "No Of Child Passengers", "1", "2", "3" }));
        nocp_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nocp_cbActionPerformed(evt);
            }
        });
        jPanel1.add(nocp_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 720, -1, -1));

        jLabel19.setForeground(new java.awt.Color(0, 255, 0));
        jLabel19.setText("Click Here For Children Below 5 Years(For Whoom Ticket Is Not Issued)");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 720, 350, 20));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 1230, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Upto_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upto_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Upto_TFActionPerformed

    private void Sex_CB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sex_CB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sex_CB4ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void captcha_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captcha_btnActionPerformed
String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Random rnd= new Random();
StringBuilder sb = new StringBuilder(8);
for (int i=0;i<8;i++)
{sb.append(contain.charAt(rnd.nextInt(contain.length())));}
String random =sb.toString();
Cap_LB.setText(random);// TODO add your handling code here:
    }//GEN-LAST:event_captcha_btnActionPerformed

    private void replan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replan_btnActionPerformed
irctcbookingsearch i1 =new irctcbookingsearch();
irctcbookingsearch.Uid_TF.setText(this.Uid_LB.getText());
i1.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_replan_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
Name_TF.setText("");Name_TF1.setText("");Name_TF2.setText("");Name_TF3.setText("");Name_TF4.setText("");Name_TF5.setText("");Age_TF.setText("");Age_TF1.setText("");Age_TF2.setText("");Age_TF3.setText("");Age_TF4.setText("");Age_TF5.setText("");Cname_TF2.setText("");Cname_TF1.setText("");Cname_TF.setText("");CAge_TF2.setText("");CAge_TF.setText("");CAge_TF1.setText("");Cap_TF.setText("");Mob_TF.setText("");
cb2.setSelected(false);cb1.setSelected(false);
RB_2.setSelected(false);RB_1.setSelected(false);RB3.setSelected(true);
Sex_CB5.setSelectedIndex(0);Sex_CB.setSelectedIndex(0);Sex_CB1.setSelectedIndex(0);jComboBox4.setSelectedIndex(0);Sex_CB2.setSelectedIndex(0);Sex_CB3.setSelectedIndex(0);Sex_CB4.setSelectedIndex(0);Ctz_CB4.setSelectedIndex(0);Ctz_CB.setSelectedIndex(0);Ctz_CB1.setSelectedIndex(0);Ctz_CB2.setSelectedIndex(0);Ctz_CB3.setSelectedIndex(0);Ctz_CB5.setSelectedIndex(0);Id_CB5.setSelectedIndex(0);Id_CB.setSelectedIndex(0);Id_CB1.setSelectedIndex(0);Id_CB2.setSelectedIndex(0);Id_CB3.setSelectedIndex(0);Id_CB4.setSelectedIndex(0);sex_CB2.setSelectedIndex(0);sex_CB.setSelectedIndex(0);sex_CB1.setSelectedIndex(0);
nocp_cb.setSelectedIndex(0);Nop_Cb.setSelectedIndex(0);
String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
Random rnd= new Random();
StringBuilder sb = new StringBuilder(8);
for (int i=0;i<8;i++)
{sb.append(contain.charAt(rnd.nextInt(contain.length())));}
String random =sb.toString();
Cap_LB.setText(random);// TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void next_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_next_btnActionPerformed

        
            if (Nop_Cb.getSelectedIndex() == 0)
{
JOptionPane.showMessageDialog(null, "Please Select At Least One Passenger");

}

        else if(Sex_CB.getSelectedIndex() == 0 || Ctz_CB.getSelectedIndex() == 0 || Id_CB.getSelectedIndex() == 0 || Name_TF.getText().length() <= 0 || Age_TF.getText().length() <= 0)
{
JOptionPane.showMessageDialog(null, "Please Fill Details About At Least One Passenger To Continue");

}

        else if(Mob_TF.getText().length() == 0 || Mob_TF.getText().length() > 10|| Mob_TF.getText().length() < 10)
{
    JOptionPane.showMessageDialog(null, "Please Enter Valid Mobile Number");
    
}
        else if(!Cap_LB.getText().equals(Cap_TF.getText()))
            
{
JOptionPane.showMessageDialog(null, "Incorrect Captcha");
}
        
 else{
         if(Nop_Cb.getSelectedIndex() == 1)
        {
  passendetail a1=new passendetail();
  if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
  passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
           a1.setVisible(true);
  this.setVisible(false);}

        else if(Nop_Cb.getSelectedIndex() == 2)
        {
  passendetail a1=new passendetail();
  if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
   passendetail.Name_TF1.setText(this.Name_TF1.getText());
   passendetail.Age_TF1.setText(this.Age_TF1.getText());
   passendetail.Sr_TF1.setText(this.Sr_LB1.getText());
   passendetail.Sex_TF1.setText((String) this.Sex_CB1.getSelectedItem());
   passendetail.S_TF1.setText(this.Sr_LB1.getText());
   passendetail.Ctz_TF1.setText((String) this.Ctz_CB1.getSelectedItem());
   passendetail.Id_TF1.setText((String) this.Id_CB1.getSelectedItem());
    passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
   a1.setVisible(true);this.setVisible(false);}

        else if(Nop_Cb.getSelectedIndex() == 3)
        {
 passendetail a1=new passendetail();
 if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
   passendetail.Name_TF1.setText(this.Name_TF1.getText());
   passendetail.Age_TF1.setText(this.Age_TF1.getText());
   passendetail.Sr_TF1.setText(this.Sr_LB1.getText());
   passendetail.Sex_TF1.setText((String) this.Sex_CB1.getSelectedItem());
   passendetail.S_TF1.setText(this.Sr_LB1.getText());
   passendetail.Ctz_TF1.setText((String) this.Ctz_CB1.getSelectedItem());
   passendetail.Id_TF1.setText((String) this.Id_CB1.getSelectedItem());
    passendetail.Name_TF2.setText(this.Name_TF2.getText());
   passendetail.Age_TF2.setText(this.Age_TF2.getText());
   passendetail.Sr_TF2.setText(this.Sr_LB2.getText());
   passendetail.Sex_TF2.setText((String) this.Sex_CB2.getSelectedItem());
   passendetail.S_TF2.setText(this.Sr_LB2.getText());
   passendetail.Ctz_TF2.setText((String) this.Ctz_CB2.getSelectedItem());
   passendetail.Id_TF2.setText((String) this.Id_CB2.getSelectedItem());
    passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
   a1.setVisible(true);this.setVisible(false);
 }

        else if(Nop_Cb.getSelectedIndex() == 4)
        {
 passendetail a1=new passendetail();
 if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
   passendetail.Name_TF1.setText(this.Name_TF1.getText());
   passendetail.Age_TF1.setText(this.Age_TF1.getText());
   passendetail.Sr_TF1.setText(this.Sr_LB1.getText());
   passendetail.Sex_TF1.setText((String) this.Sex_CB1.getSelectedItem());
   passendetail.S_TF1.setText(this.Sr_LB1.getText());
   passendetail.Ctz_TF1.setText((String) this.Ctz_CB1.getSelectedItem());
   passendetail.Id_TF1.setText((String) this.Id_CB1.getSelectedItem());
    passendetail.Name_TF2.setText(this.Name_TF2.getText());
   passendetail.Age_TF2.setText(this.Age_TF2.getText());
   passendetail.Sr_TF2.setText(this.Sr_LB2.getText());
   passendetail.Sex_TF2.setText((String) this.Sex_CB2.getSelectedItem());
   passendetail.S_TF2.setText(this.Sr_LB2.getText());
   passendetail.Ctz_TF2.setText((String) this.Ctz_CB2.getSelectedItem());
   passendetail.Id_TF2.setText((String) this.Id_CB2.getSelectedItem());
   passendetail.Name_TF3.setText(this.Name_TF3.getText());
   passendetail.Age_TF3.setText(this.Age_TF3.getText());
   passendetail.Sr_TF3.setText(this.Sr_LB3.getText());
   passendetail.Sex_TF3.setText((String) this.Sex_CB3.getSelectedItem());
   passendetail.S_TF3.setText(this.Sr_LB3.getText());
   passendetail.Ctz_TF3.setText((String) this.Ctz_CB3.getSelectedItem());
   passendetail.Id_TF3.setText((String) this.Id_CB3.getSelectedItem());
    passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
   a1.setVisible(true);this.setVisible(false);
 }

        else if(Nop_Cb.getSelectedIndex() == 5)
        {
 passendetail a1=new passendetail();
 if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
   passendetail.Name_TF1.setText(this.Name_TF1.getText());
   passendetail.Age_TF1.setText(this.Age_TF1.getText());
   passendetail.Sr_TF1.setText(this.Sr_LB1.getText());
   passendetail.Sex_TF1.setText((String) this.Sex_CB1.getSelectedItem());
   passendetail.S_TF1.setText(this.Sr_LB1.getText());
   passendetail.Ctz_TF1.setText((String) this.Ctz_CB1.getSelectedItem());
   passendetail.Id_TF1.setText((String) this.Id_CB1.getSelectedItem());
    passendetail.Name_TF2.setText(this.Name_TF2.getText());
   passendetail.Age_TF2.setText(this.Age_TF2.getText());
   passendetail.Sr_TF2.setText(this.Sr_LB2.getText());
   passendetail.Sex_TF2.setText((String) this.Sex_CB2.getSelectedItem());
   passendetail.S_TF2.setText(this.Sr_LB2.getText());
   passendetail.Ctz_TF2.setText((String) this.Ctz_CB2.getSelectedItem());
   passendetail.Id_TF2.setText((String) this.Id_CB2.getSelectedItem());
   passendetail.Name_TF3.setText(this.Name_TF3.getText());
   passendetail.Age_TF3.setText(this.Age_TF3.getText());
   passendetail.Sr_TF3.setText(this.Sr_LB3.getText());
   passendetail.Sex_TF3.setText((String) this.Sex_CB3.getSelectedItem());
   passendetail.S_TF3.setText(this.Sr_LB3.getText());
   passendetail.Ctz_TF3.setText((String) this.Ctz_CB3.getSelectedItem());
   passendetail.Id_TF3.setText((String) this.Id_CB3.getSelectedItem());
passendetail.Name_TF4.setText(this.Name_TF4.getText());
   passendetail.Age_TF4.setText(this.Age_TF4.getText());
   passendetail.Sr_TF4.setText(this.Sr_LB4.getText());
   passendetail.Sex_TF4.setText((String) this.Sex_CB4.getSelectedItem());
   passendetail.S_TF4.setText(this.Sr_LB4.getText());
   passendetail.Ctz_TF4.setText((String) this.Ctz_CB4.getSelectedItem());
   passendetail.Id_TF4.setText((String) this.Id_CB4.getSelectedItem());
    passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
   a1.setVisible(true);this.setVisible(false);
 }

        else if(Nop_Cb.getSelectedIndex() == 6)
        {
 passendetail a1=new passendetail();
 if(nocp_cb.getSelectedIndex()==1){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 }
 else  if (nocp_cb.getSelectedIndex() == 2) {
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 }
 else if(nocp_cb.getSelectedIndex()==3){
 passendetail.sr_TF.setText(this.S_LB.getText());
 passendetail.name_TF.setText(this.Cname_TF.getText());
 passendetail.age_TF.setText(this.CAge_TF.getText());
 passendetail.sex_TF.setText((String) this.sex_CB.getSelectedItem());
 passendetail.sr_TF1.setText(this.S_LB1.getText());
 passendetail.name_TF1.setText(this.Cname_TF1.getText());
 passendetail.age_TF1.setText(this.CAge_TF1.getText());
 passendetail.sex_TF1.setText((String) this.sex_CB1.getSelectedItem());
 passendetail.sr_TF2.setText(this.S_LB2.getText());
 passendetail.name_TF2.setText(this.Cname_TF2.getText());
 passendetail.age_TF2.setText(this.CAge_TF2.getText());
 passendetail.sex_TF2.setText((String) this.sex_CB2.getSelectedItem());
 }
   passendetail.Name_TF.setText(this.Name_TF.getText());
   passendetail.Age_TF.setText(this.Age_TF.getText());
   passendetail.Sr_TF.setText(this.Sr_LB.getText());
   passendetail.Sex_TF.setText((String) this.Sex_CB.getSelectedItem());
   passendetail.S_TF.setText(this.Sr_LB.getText());
   passendetail.Ctz_TF.setText((String) this.Ctz_CB.getSelectedItem());
   passendetail.Id_TF.setText((String) this.Id_CB.getSelectedItem());
   passendetail.Name_TF1.setText(this.Name_TF1.getText());
   passendetail.Age_TF1.setText(this.Age_TF1.getText());
   passendetail.Sr_TF1.setText(this.Sr_LB1.getText());
   passendetail.Sex_TF1.setText((String) this.Sex_CB1.getSelectedItem());
   passendetail.S_TF1.setText(this.Sr_LB1.getText());
   passendetail.Ctz_TF1.setText((String) this.Ctz_CB1.getSelectedItem());
   passendetail.Id_TF1.setText((String) this.Id_CB1.getSelectedItem());
    passendetail.Name_TF2.setText(this.Name_TF2.getText());
   passendetail.Age_TF2.setText(this.Age_TF2.getText());
   passendetail.Sr_TF2.setText(this.Sr_LB2.getText());
   passendetail.Sex_TF2.setText((String) this.Sex_CB2.getSelectedItem());
   passendetail.S_TF2.setText(this.Sr_LB2.getText());
   passendetail.Ctz_TF2.setText((String) this.Ctz_CB2.getSelectedItem());
   passendetail.Id_TF2.setText((String) this.Id_CB2.getSelectedItem());
   passendetail.Name_TF3.setText(this.Name_TF3.getText());
   passendetail.Age_TF3.setText(this.Age_TF3.getText());
   passendetail.Sr_TF3.setText(this.Sr_LB3.getText());
   passendetail.Sex_TF3.setText((String) this.Sex_CB3.getSelectedItem());
   passendetail.S_TF3.setText(this.Sr_LB3.getText());
   passendetail.Ctz_TF3.setText((String) this.Ctz_CB3.getSelectedItem());
   passendetail.Id_TF3.setText((String) this.Id_CB3.getSelectedItem());
passendetail.Name_TF4.setText(this.Name_TF4.getText());
   passendetail.Age_TF4.setText(this.Age_TF4.getText());
   passendetail.Sr_TF4.setText(this.Sr_LB4.getText());
   passendetail.Sex_TF4.setText((String) this.Sex_CB4.getSelectedItem());
   passendetail.S_TF4.setText(this.Sr_LB4.getText());
   passendetail.Ctz_TF4.setText((String) this.Ctz_CB4.getSelectedItem());
   passendetail.Id_TF4.setText((String) this.Id_CB4.getSelectedItem());
   passendetail.Name_TF5.setText(this.Name_TF5.getText());
   passendetail.Age_TF5.setText(this.Age_TF5.getText());
   passendetail.Sr_TF5.setText(this.Sr_LB5.getText());
   passendetail.Sex_TF5.setText((String) this.Sex_CB5.getSelectedItem());
   passendetail.S_TF5.setText(this.Sr_LB5.getText());
   passendetail.Ctz_TF5.setText((String) this.Ctz_CB5.getSelectedItem());
   passendetail.Id_TF5.setText((String) this.Id_CB5.getSelectedItem());
    passendetail.From_TF.setText(this.From_TF.getText());
   passendetail.Trname_TF.setText(this.Trname_TF.getText());
  passendetail.BP_TF.setText(this.BP_TF.getText());
   passendetail.Avail_TF.setText(this.Avail_TF.getText());
    passendetail.Dist_TF.setText(this.Dist_TF.getText());
    passendetail.To_TF.setText(this.To_TF.getText());
    passendetail.Class_TF.setText(this.Class_TF.getText());
    passendetail.Resupto_TF.setText(this.Upto_TF.getText());
    passendetail.Quota_TF.setText(this.Quota_TF.getText());
    passendetail.Trno_TF.setText(this.Trno_TF.getText());
    passendetail.Date_TF.setText(this.Date_TF.getText());
    passendetail.Type_TF.setText(this.Type_TF.getText());
    passendetail.nop_TF.setText((String) this.Nop_Cb.getSelectedItem());
    passendetail.Uid_LB.setText(Uid_LB.getText());
   a1.setVisible(true);this.setVisible(false);
 }
  
            }
  
   // TODO add your handling code here:
    }//GEN-LAST:event_next_btnActionPerformed

    private void Name_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TF1ActionPerformed

    private void RB_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RB_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RB_2ActionPerformed

    private void Name_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_TFActionPerformed

    private void Nop_CbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Nop_CbActionPerformed
 if(Nop_Cb.getSelectedIndex()==0)
 {
     Sex_CB5.setEnabled(false);Sex_CB1.setEnabled(false);jComboBox4.setEnabled(false);Sex_CB2.setEnabled(false); Sex_CB3.setEnabled(false); Sex_CB4.setEnabled(false);Ctz_CB4.setEnabled(false);Ctz_CB1.setEnabled(false); Ctz_CB2.setEnabled(false); Ctz_CB3.setEnabled(false); Ctz_CB5.setEnabled(false); Id_CB5.setEnabled(false);Id_CB1.setEnabled(false); Id_CB2.setEnabled(false); Id_CB3.setEnabled(false);

   Id_CB4.setEnabled(false);Sex_CB5.setVisible(false);Sex_CB1.setVisible(false);jComboBox4.setVisible(false);Sex_CB2.setVisible(false); Sex_CB3.setVisible(false); Sex_CB4.setVisible(false);Ctz_CB4.setVisible(false);Ctz_CB1.setVisible(false);Ctz_CB2.setVisible(false);Ctz_CB3.setVisible(false); Ctz_CB5.setVisible(false); Id_CB5.setVisible(false); Id_CB1.setVisible(false); Id_CB2.setVisible(false); Id_CB3.setVisible(false);

    Id_CB4.setVisible(false); Name_TF1.setEnabled(false);Name_TF2.setEnabled(false);Name_TF3.setEnabled(false);Name_TF4.setEnabled(false);Name_TF5.setEnabled(false);Age_TF5.setEnabled(false);Age_TF1.setEnabled(false);Age_TF2.setEnabled(false);Age_TF3.setEnabled(false);Age_TF4.setEnabled(false);

     Name_TF1.setVisible(false);Name_TF2.setVisible(false);Name_TF3.setVisible(false);Name_TF4.setVisible(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);Age_TF1.setVisible(false);Age_TF2.setVisible(false);Age_TF3.setVisible(false);Age_TF4.setVisible(false);

     Sr_LB1.setEnabled(false);Sr_LB2.setEnabled(false);Sr_LB3.setEnabled(false);Sr_LB5.setEnabled(false);Sr_LB4.setEnabled(false);
     Sr_LB1.setVisible(false);Sr_LB2.setVisible(false);Sr_LB3.setVisible(false);Sr_LB5.setVisible(false);Sr_LB4.setVisible(false);



     sex_CB2.setEnabled(false);sex_CB1.setEnabled(false);sex_CB2.setVisible(false);sex_CB1.setVisible(false);
     CAge_TF1.setEnabled(false);Cname_TF2.setEnabled(false);CAge_TF2.setEnabled(false);Cname_TF1.setEnabled(false);
     CAge_TF1.setVisible(false);Cname_TF2.setVisible(false);CAge_TF2.setVisible(false);Cname_TF1.setVisible(false);
     S_LB1.setEnabled(false);S_LB1.setVisible(false);S_LB2.setEnabled(false);S_LB2.setVisible(false);
     Sex_CB.setEnabled(false);Ctz_CB.setEnabled(false);Id_CB.setEnabled(false);Sex_CB.setVisible(false);Ctz_CB.setVisible(false);Id_CB.setVisible(false);
Sr_LB.setEnabled(false);Sr_LB.setVisible(false);
Age_TF.setEnabled(false);Name_TF.setEnabled(false);Age_TF.setVisible(false);Name_TF.setVisible(false);

 }
 else if (Nop_Cb.getSelectedIndex() == 1) {
   Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);
  Sex_CB1.setVisible(false);Sex_CB1.setEnabled(false);Ctz_CB1.setVisible(false);Id_CB1.setVisible(false);Ctz_CB1.setEnabled(false);Id_CB1.setEnabled(false);
  Age_TF1.setEnabled(false);Name_TF1.setEnabled(false);Name_TF1.setVisible(false);Age_TF1.setVisible(false);
  Sr_LB1.setEnabled(false);Sr_LB1.setVisible(false);
  Sex_CB2.setVisible(false);Sex_CB2.setEnabled(false);Ctz_CB2.setVisible(false);Id_CB2.setVisible(false);Ctz_CB2.setEnabled(false);Id_CB2.setEnabled(false);
  Age_TF2.setEnabled(false);Name_TF2.setEnabled(false);Name_TF2.setVisible(false);Age_TF2.setVisible(false);
  Sr_LB2.setEnabled(false);Sr_LB2.setVisible(false);
   Sex_CB3.setVisible(false);Sex_CB3.setEnabled(false);Ctz_CB3.setVisible(false);Id_CB3.setVisible(false);Ctz_CB3.setEnabled(false);Id_CB3.setEnabled(false);
  Age_TF3.setEnabled(false);Name_TF3.setEnabled(false);Name_TF3.setVisible(false);Age_TF3.setVisible(false);
  Sr_LB3.setEnabled(false);Sr_LB3.setVisible(false);
  Sex_CB4.setVisible(false);Sex_CB4.setEnabled(false);Ctz_CB4.setVisible(false);Id_CB4.setVisible(false);Ctz_CB4.setEnabled(false);Id_CB4.setEnabled(false);
  Age_TF4.setEnabled(false);Name_TF4.setEnabled(false);Name_TF4.setVisible(false);Age_TF4.setVisible(false);
  Sr_LB4.setEnabled(false);Sr_LB4.setVisible(false);
  Sex_CB5.setVisible(false);Sex_CB5.setEnabled(false);Ctz_CB5.setVisible(false);Id_CB5.setVisible(false);Ctz_CB5.setEnabled(false);Id_CB5.setEnabled(false);
  Age_TF5.setEnabled(false);Name_TF5.setEnabled(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB5.setEnabled(false);Sr_LB5.setVisible(false);
   }
   else if(Nop_Cb.getSelectedIndex()==2)
 {Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);
     Sex_CB1.setVisible(true);Sex_CB1.setEnabled(true);Ctz_CB1.setVisible(true);Id_CB1.setVisible(true);Ctz_CB1.setEnabled(true);Id_CB1.setEnabled(true);
  Age_TF1.setEnabled(true);Name_TF1.setEnabled(true);Name_TF1.setVisible(true);Age_TF1.setVisible(true);
  Sr_LB1.setEnabled(true);Sr_LB1.setVisible(true);
  Sex_CB2.setVisible(false);Sex_CB2.setEnabled(false);Ctz_CB2.setVisible(false);Id_CB2.setVisible(false);Ctz_CB2.setEnabled(false);Id_CB2.setEnabled(false);
  Age_TF2.setEnabled(false);Name_TF2.setEnabled(false);Name_TF2.setVisible(false);Age_TF2.setVisible(false);
  Sr_LB2.setEnabled(false);Sr_LB2.setVisible(false);
  Sex_CB3.setVisible(false);Sex_CB3.setEnabled(false);Ctz_CB3.setVisible(false);Id_CB3.setVisible(false);Ctz_CB3.setEnabled(false);Id_CB3.setEnabled(false);
  Age_TF3.setEnabled(false);Name_TF3.setEnabled(false);Name_TF3.setVisible(false);Age_TF3.setVisible(false);
  Sr_LB3.setEnabled(false);Sr_LB3.setVisible(false);
  Sex_CB4.setVisible(false);Sex_CB4.setEnabled(false);Ctz_CB4.setVisible(false);Id_CB4.setVisible(false);Ctz_CB4.setEnabled(false);Id_CB4.setEnabled(false);
  Age_TF4.setEnabled(false);Name_TF4.setEnabled(false);Name_TF4.setVisible(false);Age_TF4.setVisible(false);
  Sr_LB4.setEnabled(false);Sr_LB4.setVisible(false);
  Sex_CB5.setVisible(false);Sex_CB5.setEnabled(false);Ctz_CB5.setVisible(false);Id_CB5.setVisible(false);Ctz_CB5.setEnabled(false);Id_CB5.setEnabled(false);
  Age_TF5.setEnabled(false);Name_TF5.setEnabled(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB5.setEnabled(false);Sr_LB5.setVisible(false);
 }
   else if(Nop_Cb.getSelectedIndex()==3){
   Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);
  Sex_CB2.setEnabled(true);Ctz_CB2.setEnabled(true);Id_CB2.setEnabled(true);Sex_CB2.setVisible(true);Ctz_CB2.setVisible(true);Id_CB2.setVisible(true);
Age_TF2.setEnabled(true);Name_TF2.setEnabled(true);Age_TF2.setVisible(true);Name_TF2.setVisible(true);
Sr_LB2.setEnabled(true);Sr_LB2.setVisible(true);
Sex_CB1.setVisible(true);Sex_CB1.setEnabled(true);Ctz_CB1.setVisible(true);Id_CB1.setVisible(true);Ctz_CB1.setEnabled(true);Id_CB1.setEnabled(true);
  Age_TF1.setEnabled(true);Name_TF1.setEnabled(true);Name_TF1.setVisible(true);Age_TF1.setVisible(true);
  Sr_LB1.setEnabled(true);Sr_LB1.setVisible(true);
  Sex_CB3.setVisible(false);Sex_CB3.setEnabled(false);Ctz_CB3.setVisible(false);Id_CB3.setVisible(false);Ctz_CB3.setEnabled(false);Id_CB3.setEnabled(false);
  Age_TF3.setEnabled(false);Name_TF3.setEnabled(false);Name_TF3.setVisible(false);Age_TF3.setVisible(false);
  Sr_LB3.setEnabled(false);Sr_LB3.setVisible(false);
  Sex_CB4.setVisible(false);Sex_CB4.setEnabled(false);Ctz_CB4.setVisible(false);Id_CB4.setVisible(false);Ctz_CB4.setEnabled(false);Id_CB4.setEnabled(false);
  Age_TF4.setEnabled(false);Name_TF4.setEnabled(false);Name_TF4.setVisible(false);Age_TF4.setVisible(false);
  Sr_LB4.setEnabled(false);Sr_LB4.setVisible(false);
  Sex_CB5.setVisible(false);Sex_CB5.setEnabled(false);Ctz_CB5.setVisible(false);Id_CB5.setVisible(false);Ctz_CB5.setEnabled(false);Id_CB5.setEnabled(false);
  Age_TF5.setEnabled(false);Name_TF5.setEnabled(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB5.setEnabled(false);Sr_LB5.setVisible(false);
   }
   else if(Nop_Cb.getSelectedIndex()==4){
   Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);
  Sex_CB2.setEnabled(true);Ctz_CB2.setEnabled(true);Id_CB2.setEnabled(true);Sex_CB2.setVisible(true);Ctz_CB2.setVisible(true);Id_CB2.setVisible(true);
Age_TF2.setEnabled(true);Name_TF2.setEnabled(true);Age_TF2.setVisible(true);Name_TF2.setVisible(true);
Sr_LB2.setEnabled(true);Sr_LB2.setVisible(true);
Sex_CB1.setVisible(true);Sex_CB1.setEnabled(true);Ctz_CB1.setVisible(true);Id_CB1.setVisible(true);Ctz_CB1.setEnabled(true);Id_CB1.setEnabled(true);
  Age_TF1.setEnabled(true);Name_TF1.setEnabled(true);Name_TF1.setVisible(true);Age_TF1.setVisible(true);
  Sr_LB1.setEnabled(true);Sr_LB1.setVisible(true);
  Sex_CB3.setEnabled(true);Ctz_CB3.setEnabled(true);Id_CB3.setEnabled(true);Sex_CB3.setVisible(true);Ctz_CB3.setVisible(true);Id_CB3.setVisible(true);
Sr_LB3.setEnabled(true);Sr_LB3.setVisible(true);
Name_TF3.setEnabled(true);Age_TF3.setEnabled(true);Name_TF3.setVisible(true);Age_TF3.setVisible(true);
Sex_CB4.setVisible(false);Sex_CB4.setEnabled(false);Ctz_CB4.setVisible(false);Id_CB4.setVisible(false);Ctz_CB4.setEnabled(false);Id_CB4.setEnabled(false);
  Age_TF4.setEnabled(false);Name_TF4.setEnabled(false);Name_TF4.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB4.setEnabled(false);Sr_LB4.setVisible(false);
  Sex_CB5.setVisible(false);Sex_CB5.setEnabled(false);Ctz_CB5.setVisible(false);Id_CB5.setVisible(false);Ctz_CB5.setEnabled(false);Id_CB5.setEnabled(false);
  Age_TF5.setEnabled(false);Name_TF5.setEnabled(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB5.setEnabled(false);Sr_LB5.setVisible(false);
   }
   else if(Nop_Cb.getSelectedIndex()==5){
   Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);Sex_CB2.setEnabled(true);Ctz_CB2.setEnabled(true);Id_CB2.setEnabled(true);Sex_CB2.setVisible(true);Ctz_CB2.setVisible(true);Id_CB2.setVisible(true);
Age_TF2.setEnabled(true);Name_TF2.setEnabled(true);Age_TF2.setVisible(true);Name_TF2.setVisible(true);
Sr_LB2.setEnabled(true);Sr_LB2.setVisible(true);
Sex_CB1.setVisible(true);Sex_CB1.setEnabled(true);Ctz_CB1.setVisible(true);Id_CB1.setVisible(true);Ctz_CB1.setEnabled(true);Id_CB1.setEnabled(true);
  Age_TF1.setEnabled(true);Name_TF1.setEnabled(true);Name_TF1.setVisible(true);Age_TF1.setVisible(true);
  Sr_LB1.setEnabled(true);Sr_LB1.setVisible(true);
  Sex_CB3.setEnabled(true);Ctz_CB3.setEnabled(true);Id_CB3.setEnabled(true);Sex_CB3.setVisible(true);Ctz_CB3.setVisible(true);Id_CB3.setVisible(true);
Sr_LB3.setEnabled(true);Sr_LB3.setVisible(true);
Name_TF3.setEnabled(true);Age_TF3.setEnabled(true);Name_TF3.setVisible(true);Age_TF3.setVisible(true);
  Sex_CB4.setEnabled(true);Ctz_CB4.setEnabled(true);Id_CB4.setEnabled(true);Sex_CB4.setVisible(true);Ctz_CB4.setVisible(true);Id_CB4.setVisible(true);
Sr_LB4.setEnabled(true);Sr_LB4.setVisible(true);
Name_TF4.setEnabled(true);Age_TF4.setEnabled(true);Name_TF4.setVisible(true);Age_TF4.setVisible(true);
Sex_CB5.setVisible(false);Sex_CB5.setEnabled(false);Ctz_CB5.setVisible(false);Id_CB5.setVisible(false);Ctz_CB5.setEnabled(false);Id_CB5.setEnabled(false);
  Age_TF5.setEnabled(false);Name_TF5.setEnabled(false);Name_TF5.setVisible(false);Age_TF5.setVisible(false);
  Sr_LB5.setEnabled(false);Sr_LB5.setVisible(false);
   }
   else if(Nop_Cb.getSelectedIndex()==6){
   Sex_CB.setVisible(true);Sex_CB.setEnabled(true);Ctz_CB.setVisible(true);Id_CB.setVisible(true);Ctz_CB.setEnabled(true);Id_CB.setEnabled(true);
  Age_TF.setEnabled(true);Name_TF.setEnabled(true);Name_TF.setVisible(true);Age_TF.setVisible(true);
  Sr_LB.setEnabled(true);Sr_LB.setVisible(true);
  Sex_CB2.setEnabled(true);Ctz_CB2.setEnabled(true);Id_CB2.setEnabled(true);Sex_CB2.setVisible(true);Ctz_CB2.setVisible(true);Id_CB2.setVisible(true);
Age_TF2.setEnabled(true);Name_TF2.setEnabled(true);Age_TF2.setVisible(true);Name_TF2.setVisible(true);
Sr_LB2.setEnabled(true);Sr_LB2.setVisible(true);
Sex_CB1.setVisible(true);Sex_CB1.setEnabled(true);Ctz_CB1.setVisible(true);Id_CB1.setVisible(true);Ctz_CB1.setEnabled(true);Id_CB1.setEnabled(true);
  Age_TF1.setEnabled(true);Name_TF1.setEnabled(true);Name_TF1.setVisible(true);Age_TF1.setVisible(true);
  Sr_LB1.setEnabled(true);Sr_LB1.setVisible(true);
  Sex_CB3.setEnabled(true);Ctz_CB3.setEnabled(true);Id_CB3.setEnabled(true);Sex_CB3.setVisible(true);Ctz_CB3.setVisible(true);Id_CB3.setVisible(true);
Sr_LB3.setEnabled(true);Sr_LB3.setVisible(true);
Name_TF3.setEnabled(true);Age_TF3.setEnabled(true);Name_TF3.setVisible(true);Age_TF3.setVisible(true);
  Sex_CB4.setEnabled(true);Ctz_CB4.setEnabled(true);Id_CB4.setEnabled(true);Sex_CB4.setVisible(true);Ctz_CB4.setVisible(true);Id_CB4.setVisible(true);
Sr_LB4.setEnabled(true);Sr_LB4.setVisible(true);
Name_TF4.setEnabled(true);Age_TF4.setEnabled(true);Name_TF4.setVisible(true);Age_TF4.setVisible(true);
Sex_CB5.setEnabled(true);Ctz_CB5.setEnabled(true);Id_CB5.setEnabled(true);Sex_CB5.setVisible(true);Ctz_CB5.setVisible(true);Id_CB5.setVisible(true);
Sr_LB5.setEnabled(true);Sr_LB5.setVisible(true);
Age_TF5.setEnabled(true);Name_TF5.setEnabled(true);Age_TF5.setVisible(true);Name_TF5.setVisible(true);
   }
 else if(Nop_Cb.getSelectedIndex()==0){


    
 }
   // TODO add your handling code here:
    }//GEN-LAST:event_Nop_CbActionPerformed

    private void Sex_CBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sex_CBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Sex_CBActionPerformed

    private void Id_CB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_CB2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_CB2ActionPerformed

    private void Id_CB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Id_CB1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Id_CB1ActionPerformed

    private void nocp_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nocp_cbActionPerformed
if(nocp_cb.getSelectedIndex()==0)
{
    sex_CB.setEnabled(false);sex_CB.setVisible(false);
S_LB.setEnabled(false);S_LB.setVisible(false);
Cname_TF.setEnabled(false);CAge_TF.setEnabled(false);Cname_TF.setVisible(false);CAge_TF.setVisible(false);
sex_CB1.setEnabled(false);sex_CB1.setVisible(false);
S_LB1.setEnabled(false);S_LB1.setVisible(false);
Cname_TF1.setEnabled(false);CAge_TF1.setEnabled(false);Cname_TF1.setVisible(false);CAge_TF1.setVisible(false);
sex_CB2.setEnabled(false);sex_CB2.setVisible(false);
S_LB2.setEnabled(false);S_LB2.setVisible(false);
CAge_TF2.setEnabled(false);Cname_TF2.setEnabled(false);CAge_TF2.setVisible(false);Cname_TF2.setVisible(false);

}
        else if(nocp_cb.getSelectedIndex() == 1)
{

     sex_CB.setEnabled(true);sex_CB.setVisible(true);
S_LB.setEnabled(true);S_LB.setVisible(true);
Cname_TF.setEnabled(true);CAge_TF.setEnabled(true);Cname_TF.setVisible(true);CAge_TF.setVisible(true);
sex_CB2.setEnabled(false);sex_CB1.setEnabled(false);sex_CB2.setVisible(false);sex_CB1.setVisible(false);
     CAge_TF1.setEnabled(false);Cname_TF2.setEnabled(false);CAge_TF2.setEnabled(false);Cname_TF1.setEnabled(false);
     CAge_TF1.setVisible(false);Cname_TF2.setVisible(false);CAge_TF2.setVisible(false);Cname_TF1.setVisible(false);
     S_LB1.setEnabled(false);S_LB1.setVisible(false);S_LB2.setEnabled(false);S_LB2.setVisible(false);
}
        else if(nocp_cb.getSelectedIndex() == 2)
{
sex_CB.setEnabled(true);sex_CB.setVisible(true);
S_LB.setEnabled(true);S_LB.setVisible(true);
Cname_TF.setEnabled(true);CAge_TF.setEnabled(true);Cname_TF.setVisible(true);CAge_TF.setVisible(true);
sex_CB1.setEnabled(true);sex_CB1.setVisible(true);
S_LB1.setEnabled(true);S_LB1.setVisible(true);
Cname_TF1.setEnabled(true);CAge_TF1.setEnabled(true);Cname_TF1.setVisible(true);CAge_TF1.setVisible(true);

}
        else if(nocp_cb.getSelectedIndex() == 3)
{
sex_CB.setEnabled(true);sex_CB.setVisible(true);
S_LB.setEnabled(true);S_LB.setVisible(true);
Cname_TF.setEnabled(true);CAge_TF.setEnabled(true);Cname_TF.setVisible(true);CAge_TF.setVisible(true);
sex_CB1.setEnabled(true);sex_CB1.setVisible(true);
S_LB1.setEnabled(true);S_LB1.setVisible(true);
Cname_TF1.setEnabled(true);CAge_TF1.setEnabled(true);Cname_TF1.setVisible(true);CAge_TF1.setVisible(true);
sex_CB2.setEnabled(true);sex_CB2.setVisible(true);
S_LB2.setEnabled(true);S_LB2.setVisible(true);
CAge_TF2.setEnabled(true);Cname_TF2.setEnabled(true);CAge_TF2.setVisible(true);Cname_TF2.setVisible(true);

}// TODO add your handling code here:
    }//GEN-LAST:event_nocp_cbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bookingticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Age_TF;
    public static javax.swing.JTextField Age_TF1;
    public static javax.swing.JTextField Age_TF2;
    public static javax.swing.JTextField Age_TF3;
    public static javax.swing.JTextField Age_TF4;
    public static javax.swing.JTextField Age_TF5;
    public static javax.swing.JTextField Avail_TF;
    public static javax.swing.JTextField BP_TF;
    private javax.swing.JTextField CAge_TF;
    private javax.swing.JTextField CAge_TF1;
    private javax.swing.JTextField CAge_TF2;
    private javax.swing.JLabel Cap_LB;
    private javax.swing.JTextField Cap_TF;
    public static javax.swing.JTextField Class_TF;
    private javax.swing.JTextField Cname_TF;
    private javax.swing.JTextField Cname_TF1;
    private javax.swing.JTextField Cname_TF2;
    private javax.swing.JComboBox Ctz_CB;
    private javax.swing.JComboBox Ctz_CB1;
    private javax.swing.JComboBox Ctz_CB2;
    private javax.swing.JComboBox Ctz_CB3;
    private javax.swing.JComboBox Ctz_CB4;
    private javax.swing.JComboBox Ctz_CB5;
    public static javax.swing.JTextField Date_TF;
    public static javax.swing.JTextField Dist_TF;
    public static javax.swing.JTextField From_TF;
    private javax.swing.JComboBox Id_CB;
    private javax.swing.JComboBox Id_CB1;
    private javax.swing.JComboBox Id_CB2;
    private javax.swing.JComboBox Id_CB3;
    private javax.swing.JComboBox Id_CB4;
    private javax.swing.JComboBox Id_CB5;
    private javax.swing.JTextField Mob_TF;
    private javax.swing.JTextField Name_TF;
    private javax.swing.JTextField Name_TF1;
    private javax.swing.JTextField Name_TF2;
    private javax.swing.JTextField Name_TF3;
    private javax.swing.JTextField Name_TF4;
    private javax.swing.JTextField Name_TF5;
    private javax.swing.JComboBox Nop_Cb;
    public static javax.swing.JTextField Quota_TF;
    private javax.swing.JRadioButton RB3;
    private javax.swing.JRadioButton RB_1;
    private javax.swing.JRadioButton RB_2;
    private javax.swing.JLabel S_LB;
    private javax.swing.JLabel S_LB1;
    private javax.swing.JLabel S_LB2;
    private javax.swing.JComboBox Sex_CB;
    private javax.swing.JComboBox Sex_CB1;
    private javax.swing.JComboBox Sex_CB2;
    private javax.swing.JComboBox Sex_CB3;
    private javax.swing.JComboBox Sex_CB4;
    private javax.swing.JComboBox Sex_CB5;
    private javax.swing.JLabel Sr_LB;
    private javax.swing.JLabel Sr_LB1;
    private javax.swing.JLabel Sr_LB2;
    private javax.swing.JLabel Sr_LB3;
    private javax.swing.JLabel Sr_LB4;
    private javax.swing.JLabel Sr_LB5;
    public static javax.swing.JTextField To_TF;
    public static javax.swing.JTextField Trname_TF;
    public static javax.swing.JTextField Trno_TF;
    public static javax.swing.JTextField Type_TF;
    public static javax.swing.JLabel Uid_LB;
    public static javax.swing.JTextField Upto_TF;
    private javax.swing.JLabel age_lb;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton captcha_btn;
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_lb;
    public static javax.swing.JButton next_btn;
    private javax.swing.JComboBox nocp_cb;
    private javax.swing.JButton replan_btn;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox sex_CB;
    private javax.swing.JComboBox sex_CB1;
    private javax.swing.JComboBox sex_CB2;
    private javax.swing.JLabel sex_lb;
    private javax.swing.JLabel sno_lb;
    // End of variables declaration//GEN-END:variables

    private void PlaySound(File clap) {
        throw new UnsupportedOperationException("Not yet implemented");
    }

}
