
import javax.swing.JOptionPane;
import java.sql.* ;
import java.awt.Color;

import java.io.*;
import java.util.Random;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cancel_Irctc.java
 *
 * Created on Jun 14, 2017, 1:26:04 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class Cancel_Irctc extends javax.swing.JFrame {

    /** Creates new form Cancel_Irctc */
    public Cancel_Irctc() {
        
        initComponents();
        getContentPane().setBackground(new Color(51,0,204));
        bt_panel.setEnabled(false);
  bt_panel.setVisible(false);
  uid_lb.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        trid_txt = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        reset_btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bt_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        class_txt = new javax.swing.JTextField();
        nop_txt = new javax.swing.JTextField();
        Trname_txt = new javax.swing.JTextField();
        From_txt = new javax.swing.JTextField();
        Pnr_txt = new javax.swing.JTextField();
        Trno_txt = new javax.swing.JTextField();
        dt_txt = new javax.swing.JTextField();
        To_txt = new javax.swing.JTextField();
        cancel_btn = new javax.swing.JButton();
        Cap_LB = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cap_txt = new javax.swing.JTextField();
        cap_btn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jrdt_txt = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        to_txt = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        pnr_txt = new javax.swing.JTextField();
        from_txt = new javax.swing.JTextField();
        back_btn = new javax.swing.JButton();
        uid_lb = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("PNR Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel3.setText("Journey Date");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        trid_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(trid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 91, -1));

        search_btn.setBackground(new java.awt.Color(0, 255, 0));
        search_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        search_btn.setText("Search");
        search_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        jPanel1.add(search_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, -1, 30));

        reset_btn.setBackground(new java.awt.Color(0, 255, 0));
        reset_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        reset_btn.setText("Reset");
        reset_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/irctc1.jpg"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 990, 180));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel7.setText("Booked Ticket List To Cancellation");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        bt_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booked Tickets", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 3, 18))); // NOI18N
        bt_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setText("PNR No");
        bt_panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel4.setText("Train Name");
        bt_panel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel5.setText("From Station");
        bt_panel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setText("No of Passengers");
        bt_panel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setText("Class");
        bt_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel11.setText("Train No");
        bt_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel12.setText("Date");
        bt_panel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel13.setText("To Station");
        bt_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        class_txt.setEditable(false);
        class_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(class_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 90, -1));

        nop_txt.setEditable(false);
        nop_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(nop_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 90, -1));

        Trname_txt.setEditable(false);
        Trname_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Trname_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Trname_txtActionPerformed(evt);
            }
        });
        bt_panel.add(Trname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 90, -1));

        From_txt.setEditable(false);
        From_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(From_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 90, -1));

        Pnr_txt.setEditable(false);
        Pnr_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(Pnr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 90, -1));

        Trno_txt.setEditable(false);
        Trno_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(Trno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 90, -1));

        dt_txt.setEditable(false);
        dt_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        bt_panel.add(dt_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, -1));

        To_txt.setEditable(false);
        To_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        To_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                To_txtActionPerformed(evt);
            }
        });
        bt_panel.add(To_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 90, -1));

        cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        cancel_btn.setText("Cancel Booking");
        cancel_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        bt_panel.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        Cap_LB.setFont(new java.awt.Font("Times New Roman", 3, 18));
        Cap_LB.setText("GV4HD0DP");
        bt_panel.add(Cap_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 140, 40));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel16.setText("Captcha");
        bt_panel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));
        bt_panel.add(cap_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 90, -1));

        cap_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ref.jpg"))); // NOI18N
        cap_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cap_btnActionPerformed(evt);
            }
        });
        bt_panel.add(cap_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 20, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recaptcha-edited.jpg"))); // NOI18N
        bt_panel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 100, 40));

        jPanel1.add(bt_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 610, 370));

        jrdt_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jrdt_txt.setToolTipText("[ MM/DD/YY ]");
        jrdt_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrdt_txtActionPerformed(evt);
            }
        });
        jPanel1.add(jrdt_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 90, -1));

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("Enter in Format [ MM/DD/YY ]");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel19.setText("From");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, -1, -1));

        to_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(to_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 91, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel20.setText("Transaction Id");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel21.setText("To");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, -1, -1));

        pnr_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        pnr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnr_txtActionPerformed(evt);
            }
        });
        jPanel1.add(pnr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 91, -1));

        from_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(from_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 91, -1));

        back_btn.setBackground(new java.awt.Color(0, 255, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 30));

        uid_lb.setText("jLabel8");
        jPanel1.add(uid_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 100, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 1300, 490));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1340, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
pnr_txt.setText("");
trid_txt.setText("");
trid_txt.setText("");
from_txt.setText("");
jrdt_txt.setText("");
to_txt.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
String pnr =pnr_txt.getText();
        String date=jrdt_txt.getText();
        String trid =trid_txt.getText();
       String from = from_txt.getText();
       String to= to_txt.getText();
       
try
{
    Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt;
 stmt = con.createStatement();
 String q="Select * from  bookings where PNR='"+pnr+"'";
 ResultSet rs = stmt.executeQuery(q);
 
 
 String a="";
  String b="";
  String c="";
  String d="";
  String e="";
  String f="";
  String g="";
  String h="";
  String i="";
  while(rs.next()){
    a=rs.getString(1);
    b= rs.getString(2);
    c=rs.getString(3);
    d= rs.getString(4);
    e=rs.getString(5);
    f= rs.getString(6);
    g=rs.getString(9);
    h= rs.getString(10);
    i=rs.getString(17);
if( pnr.equals(a)&&date.equals(d)&&trid.equals(i)&&from.equals(e)&&to.equals(f))
{
bt_panel.setEnabled(true);
  bt_panel.setVisible(true);
  Trno_txt.setText(b);
 Pnr_txt.setText(a);
  Trname_txt.setText(c);
dt_txt.setText(d);
From_txt.setText(e);
To_txt.setText(f);
class_txt.setText(g);
nop_txt.setText(h);


      }
 else if ( !trid.equals(i)||!date.equals(d)||!from.equals(e)||!to.equals(f)||!pnr.equals(a))
 {
  JOptionPane.showMessageDialog(null, "Please Check the details you have entered.");
     bt_panel.setEnabled(false);
  bt_panel.setVisible(false);
 }
}
}
catch(Exception e)
{
JOptionPane.showMessageDialog(null, e.getMessage());
}

// TODO add your handling code here:
    }//GEN-LAST:event_search_btnActionPerformed

    private void To_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_To_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_To_txtActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
String captcha=Cap_LB.getText();
String encaptcha=cap_txt.getText();
String pnr=Pnr_txt.getText();

try
{
 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt=con.createStatement();
 String q= "Delete from  bookings where PNR ='"+pnr+"';";
 if(encaptcha.equals(captcha))
 {JOptionPane.showMessageDialog(this, "Journey Cancelled");
  stmt.executeUpdate(q);
  bt_panel.setEnabled(false);
  bt_panel.setVisible(false);
  Pnr_txt.setText("");
Trno_txt.setText("");
Trname_txt.setText("");
dt_txt.setText("");
From_txt.setText("");
To_txt.setText("");
class_txt.setText("");
nop_txt.setText("");
trid_txt.setText("");
jrdt_txt.setText("");
this.setVisible(false);
new home().setVisible(true);
 }
 else if(encaptcha!=(captcha))
 {
 JOptionPane.showMessageDialog(this, "Please Check Captcha OR User Name");
 bt_panel.setEnabled(true);
  bt_panel.setVisible(true);
 }
}
catch(Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}/// TODO add your handling code here:
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void cap_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cap_btnActionPerformed
        String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZ";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(8);
        for (int i=0;i<8;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        Cap_LB.setText(random);// TODO add your handling code here:
}//GEN-LAST:event_cap_btnActionPerformed

    private void pnr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnr_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnr_txtActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
Object[] options={"Home","View Bookings"};
int back=JOptionPane.showOptionDialog(null,"Select Where You Want To Go ???", "Select",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,null);
   if(back==JOptionPane.YES_OPTION)  {
  home v2 =  new home();
home.TF_UID.setText(this.uid_lb.getText());
v2.setVisible(true);
this.setVisible(false);
   } 
 else if(back==JOptionPane.NO_OPTION){
     viewbookings v1 =  new viewbookings();
viewbookings.Uid_lB.setText(this.uid_lb.getText());
v1.setVisible(true);
this.setVisible(false);
  }
 else{this.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void jrdt_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrdt_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrdt_txtActionPerformed

    private void Trname_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Trname_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Trname_txtActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_Irctc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cap_LB;
    private javax.swing.JTextField From_txt;
    private javax.swing.JTextField Pnr_txt;
    private javax.swing.JTextField To_txt;
    private javax.swing.JTextField Trname_txt;
    private javax.swing.JTextField Trno_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JPanel bt_panel;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton cap_btn;
    private javax.swing.JTextField cap_txt;
    private javax.swing.JTextField class_txt;
    private javax.swing.JTextField dt_txt;
    private javax.swing.JTextField from_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jrdt_txt;
    private javax.swing.JTextField nop_txt;
    private javax.swing.JTextField pnr_txt;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField to_txt;
    private javax.swing.JTextField trid_txt;
    public static javax.swing.JLabel uid_lb;
    // End of variables declaration//GEN-END:variables

}
