
import java.sql.* ;
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * forgotpass.java
 *
 * Created on May 22, 2017, 10:03:40 AM
 */

/**
 *
 * @author Kunal Shah
 */
public class forgotpass extends javax.swing.JFrame {

    /** Creates new form forgotpass */
    public forgotpass() {
        initComponents();
         getContentPane().setBackground(new Color(51,0,204));
         cnpass_lb.setVisible(false);
          npass_lb.setVisible(false);
          npass_txt.setVisible(false);
          cnpass_txt.setVisible(false);
          changepass_btn.setVisible(false);
          showpass1.setVisible(false);
          showpass2.setVisible(false);
          SQ_Panel.setEnabled(false);
          SQ_Panel.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        changepass_btn = new javax.swing.JButton();
        uid_txt = new javax.swing.JTextField();
        uid_lb = new javax.swing.JLabel();
        fsq_btn = new javax.swing.JButton();
        cnpass_lb = new javax.swing.JLabel();
        npass_lb = new javax.swing.JLabel();
        npass_txt = new javax.swing.JPasswordField();
        cnpass_txt = new javax.swing.JPasswordField();
        shownpass_lb = new javax.swing.JLabel();
        showcnpass_lb = new javax.swing.JLabel();
        showpass1 = new javax.swing.JCheckBox();
        showpass2 = new javax.swing.JCheckBox();
        SQ_Panel = new javax.swing.JPanel();
        sq_txt = new javax.swing.JTextField();
        ans_txt = new javax.swing.JTextField();
        sq_lb = new javax.swing.JLabel();
        ans_lb = new javax.swing.JLabel();
        verify_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 573, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 8, true), "FORGOT PASSWORD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 3, 36), new java.awt.Color(0, 0, 204))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        changepass_btn.setBackground(new java.awt.Color(0, 255, 0));
        changepass_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        changepass_btn.setText("CHANGE PASSWORD");
        changepass_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        changepass_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changepass_btnActionPerformed(evt);
            }
        });
        jPanel1.add(changepass_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 373, -1));

        uid_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(uid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 77, 243, -1));

        uid_lb.setFont(new java.awt.Font("Times New Roman", 3, 18));
        uid_lb.setText("Enter User Id");
        jPanel1.add(uid_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 69, 118, 32));

        fsq_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        fsq_btn.setText("FETCH SECURITY QUESTION");
        fsq_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fsq_btnActionPerformed(evt);
            }
        });
        jPanel1.add(fsq_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 112, -1, -1));

        cnpass_lb.setFont(new java.awt.Font("Times New Roman", 3, 18));
        cnpass_lb.setText("Confirm New Password");
        jPanel1.add(cnpass_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, -1, -1));

        npass_lb.setFont(new java.awt.Font("Times New Roman", 3, 18));
        npass_lb.setText("New Password");
        jPanel1.add(npass_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        npass_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(npass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 306, 240, -1));

        cnpass_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(cnpass_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 359, 240, -1));

        shownpass_lb.setFont(new java.awt.Font("Times New Roman", 0, 14));
        shownpass_lb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(shownpass_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 332, 240, 20));

        showcnpass_lb.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(showcnpass_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 382, 240, 20));

        showpass1.setText("Show Password");
        showpass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass1ActionPerformed(evt);
            }
        });
        jPanel1.add(showpass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 305, -1, -1));

        showpass2.setText("Show Password");
        showpass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showpass2ActionPerformed(evt);
            }
        });
        jPanel1.add(showpass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 358, -1, -1));

        sq_txt.setEditable(false);
        sq_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        sq_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sq_txtActionPerformed(evt);
            }
        });

        ans_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        ans_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans_txtActionPerformed(evt);
            }
        });

        sq_lb.setFont(new java.awt.Font("Times New Roman", 3, 18));
        sq_lb.setText("Security Question");

        ans_lb.setFont(new java.awt.Font("Times New Roman", 3, 18));
        ans_lb.setText("Answer");

        verify_btn.setBackground(new java.awt.Color(255, 0, 0));
        verify_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        verify_btn.setText("VERIFY");
        verify_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        verify_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verify_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SQ_PanelLayout = new javax.swing.GroupLayout(SQ_Panel);
        SQ_Panel.setLayout(SQ_PanelLayout);
        SQ_PanelLayout.setHorizontalGroup(
            SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SQ_PanelLayout.createSequentialGroup()
                .addGroup(SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SQ_PanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sq_lb)
                            .addComponent(ans_lb))
                        .addGap(90, 90, 90)
                        .addGroup(SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ans_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sq_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SQ_PanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(verify_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        SQ_PanelLayout.setVerticalGroup(
            SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SQ_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sq_lb)
                    .addComponent(sq_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(SQ_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ans_lb)
                    .addComponent(ans_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(verify_btn)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel1.add(SQ_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 530, 130));

        back_btn.setBackground(new java.awt.Color(0, 255, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 920, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sq_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sq_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sq_txtActionPerformed

    private void fsq_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fsq_btnActionPerformed
if(uid_txt.getText().equals(""))
{JOptionPane.showMessageDialog(null, "Please enter username");}
        String uid =uid_txt.getText();
       
   try
{
    Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt;
 stmt = con.createStatement();
    String q="Select * from  accounts where U_Id = '"+ uid +"';";
   ResultSet rs = stmt.executeQuery(q);
         
   
  while(rs.next()){
    String m=rs.getString(7);
     String u= rs.getString(1);

    if( uid.equals(u))
    {
    sq_txt.setText(m);
    SQ_Panel.setEnabled(true);
    SQ_Panel.setVisible(true);
    }
 else
    { 
    SQ_Panel.setEnabled(false);
    SQ_Panel.setVisible(false);
    JOptionPane.showMessageDialog(null, "Check Your User Id");
    }
    
    }


   }
   catch(Exception e )
   {
JOptionPane.showMessageDialog(null, e.getMessage());

   }// TODO add your handling code here:
    }//GEN-LAST:event_fsq_btnActionPerformed

    private void changepass_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changepass_btnActionPerformed

String uid=uid_txt.getText();
String npass=npass_txt.getText();
String cnpass=cnpass_txt.getText();

try
{
 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt;
 stmt = con.createStatement();
    String q ="Update accounts set Password = '"+npass+"' where U_Id = '"+ uid +"';";
    if(     npass == null ? (cnpass) != null : !npass.equals(cnpass) ||npass.length()<=0||cnpass.length()<=0 ){JOptionPane.showMessageDialog(null, "Please check password!!!");}
 else if (npass.equals(cnpass)){
 stmt.executeUpdate(q);
    JOptionPane.showMessageDialog(null, "Password Updated Sucessfully");
    this.setVisible(false);
new Main().setVisible(true);

 }
        }

catch (Exception e)
{
JOptionPane.showMessageDialog(this,"Please Check New Password");

}// TODO add your handling code here:
    }//GEN-LAST:event_changepass_btnActionPerformed

    private void verify_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verify_btnActionPerformed
  if(ans_txt.getText().isEmpty())
  {JOptionPane.showMessageDialog(null, "Check Your Answer");}
String ans =ans_txt.getText();
try
{
 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt;
 stmt = con.createStatement();
    String q ="Select * from  accounts where Answer = '"+ ans +"';";
     ResultSet rs = stmt.executeQuery(q);
         
   while(rs.next()){
    String m=rs.getString(8);
    if( ans.equalsIgnoreCase(m))
    {
    cnpass_lb.setVisible(true);
    npass_lb.setVisible(true);
    npass_txt.setVisible(true);
    cnpass_txt.setVisible(true);
    changepass_btn.setVisible(true);
    showpass1.setVisible(true);
    showpass2.setVisible(true);
    }
    else
    { 
      cnpass_lb.setVisible(false);
    npass_lb.setVisible(false);
    npass_txt.setVisible(false);
    cnpass_txt.setVisible(false);
    changepass_btn.setVisible(false);
    showpass1.setVisible(false);
    showpass2.setVisible(false);
    JOptionPane.showMessageDialog(null, "Check Your Answer");
    }
            }
          
     }
catch (Exception e)
{ JOptionPane.showMessageDialog(null, e.getMessage());
}
// TODO add your handling code here:
    }//GEN-LAST:event_verify_btnActionPerformed

    private void showpass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass2ActionPerformed
if(showpass1.isSelected()){
     String pass =new String(cnpass_txt.getPassword());
     showcnpass_lb.setVisible(true);
     showcnpass_lb.setText(pass);
}else {

showcnpass_lb.setVisible(false);    }        // TODO add your handling code here:
    }//GEN-LAST:event_showpass2ActionPerformed

    private void showpass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showpass1ActionPerformed
if(showpass1.isSelected()){
     String pass =new String(npass_txt.getPassword());
     shownpass_lb.setVisible(true);
     shownpass_lb.setText(pass);
}else {

shownpass_lb.setVisible(false);    }    // TODO add your handling code here:
    }//GEN-LAST:event_showpass1ActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
this.setVisible(false);
new Main().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void ans_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans_txtActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SQ_Panel;
    private javax.swing.JLabel ans_lb;
    private javax.swing.JTextField ans_txt;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton changepass_btn;
    private javax.swing.JLabel cnpass_lb;
    private javax.swing.JPasswordField cnpass_txt;
    private javax.swing.JButton fsq_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel npass_lb;
    private javax.swing.JPasswordField npass_txt;
    private javax.swing.JLabel showcnpass_lb;
    private javax.swing.JLabel shownpass_lb;
    private javax.swing.JCheckBox showpass1;
    private javax.swing.JCheckBox showpass2;
    private javax.swing.JLabel sq_lb;
    private javax.swing.JTextField sq_txt;
    private javax.swing.JLabel uid_lb;
    private javax.swing.JTextField uid_txt;
    private javax.swing.JButton verify_btn;
    // End of variables declaration//GEN-END:variables

}
