


import java.sql.* ;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * irctcbooking.java
 *
 * Created on May 31, 2017, 10:01:28 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class irctcbookingsearch extends javax.swing.JFrame {

    /** Creates new form irctcbooking */
    public irctcbookingsearch() {
        initComponents();
Uid_TF.setVisible(false);
        class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
        trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        submit_btn = new javax.swing.JButton();
        type_cb = new javax.swing.JComboBox();
        quota_cb = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        to_cb = new javax.swing.JComboBox();
        from_cb = new javax.swing.JComboBox();
        dateselect = new datechooser.beans.DateChooserCombo();
        class_panel = new javax.swing.JPanel();
        Class_RB = new javax.swing.JRadioButton();
        Class_RB6 = new javax.swing.JRadioButton();
        Class_RB4 = new javax.swing.JRadioButton();
        Class_RB2 = new javax.swing.JRadioButton();
        Class_RB3 = new javax.swing.JRadioButton();
        Class_RB5 = new javax.swing.JRadioButton();
        TBS_panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        trlist_table = new javax.swing.JTable();
        avail_panel = new javax.swing.JPanel();
        Uid_TF = new javax.swing.JLabel();
        book_btn = new javax.swing.JButton();
        TRNAME_TF = new javax.swing.JTextField();
        TRNO_TF = new javax.swing.JTextField();
        DIST_TF = new javax.swing.JTextField();
        AVAIL_TF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        AVAIL_LB = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        trsch_panel = new javax.swing.JPanel();
        trsch_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, -1, 70));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Plan My Journey", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setLayout(null);

        jLabel3.setText("From Station:-*");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(17, 80, 100, 14);

        jLabel4.setText("To Station:-*");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(17, 116, 90, 14);

        jLabel5.setText("Journey Date:-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 150, 90, 20);

        jLabel6.setText("Quota:-");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 180, 80, 20);

        jLabel7.setText("Ticket Type:-");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 210, 80, 14);

        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reset_btn);
        reset_btn.setBounds(50, 240, 100, 23);

        submit_btn.setText("Submit");
        submit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_btnActionPerformed(evt);
            }
        });
        jPanel1.add(submit_btn);
        submit_btn.setBounds(160, 240, 100, 23);

        type_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Ticket Type", "e-ticket", "i-ticket" }));
        jPanel1.add(type_cb);
        type_cb.setBounds(120, 210, 170, 20);

        quota_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Quota", "GENERAL", "PREMIUM TATKAL", "PHYSICALLY HANDICAP", "LADIES", "TATKAL" }));
        jPanel1.add(quota_cb);
        quota_cb.setBounds(120, 180, 170, 20);

        jLabel8.setText("Search");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(36, 45, 80, 14);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/swap.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(300, 90, 20, 30);

        to_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Station\t", "AHMEDABAD JN-ADI", "NEW DELHI-NDLS", "MUMBAI CENTRAL - BCT", "JAMNAGAR - JAM", "SURAT - ST" }));
        to_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to_cbActionPerformed(evt);
            }
        });
        jPanel1.add(to_cb);
        to_cb.setBounds(120, 110, 170, 20);

        from_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Station\t", "AHMEDABAD JN-ADI", "NEW DELHI-NDLS", "MUMBAI CENTRAL - BCT", "JAMNAGAR - JAM", "SURAT - ST", " " }));
        jPanel1.add(from_cb);
        from_cb.setBounds(120, 80, 170, 20);
        jPanel1.add(dateselect);
        dateselect.setBounds(120, 150, 190, 20);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 330, 280));

        class_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Journey Class", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        buttonGroup1.add(Class_RB);
        Class_RB.setText("1A");
        Class_RB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_RBActionPerformed(evt);
            }
        });

        buttonGroup1.add(Class_RB6);
        Class_RB6.setText("2S");
        Class_RB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_RB6ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Class_RB4);
        Class_RB4.setText("CC");
        Class_RB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_RB4ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Class_RB2);
        Class_RB2.setText("2A");

        buttonGroup1.add(Class_RB3);
        Class_RB3.setText("3A");
        Class_RB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Class_RB3ActionPerformed(evt);
            }
        });

        buttonGroup1.add(Class_RB5);
        Class_RB5.setText("SL");

        javax.swing.GroupLayout class_panelLayout = new javax.swing.GroupLayout(class_panel);
        class_panel.setLayout(class_panelLayout);
        class_panelLayout.setHorizontalGroup(
            class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Class_RB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Class_RB4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Class_RB5)
                    .addComponent(Class_RB2))
                .addGap(18, 18, 18)
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Class_RB6)
                    .addComponent(Class_RB3))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        class_panelLayout.setVerticalGroup(
            class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class_RB, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Class_RB2)
                    .addComponent(Class_RB3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(class_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class_RB6)
                    .addComponent(Class_RB5)
                    .addComponent(Class_RB4))
                .addGap(102, 102, 102))
        );

        getContentPane().add(class_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 330, 100));

        TBS_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Train Between Stations", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        TBS_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trlist_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Train No", "Train Name", "From", "Departure", "To", "Arrival", "Dist.(Km)", "Travel Time", "M", "T", "W", "T", "F", "S", "S"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trlist_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trlist_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(trlist_table);

        TBS_panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 960, 193));

        getContentPane().add(TBS_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 980, 290));

        avail_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Availablity", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        avail_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        avail_panel.add(Uid_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 114, 56));

        book_btn.setFont(new java.awt.Font("Times New Roman", 1, 36));
        book_btn.setText("Book Now");
        book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_btnActionPerformed(evt);
            }
        });
        avail_panel.add(book_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 220, 200));

        TRNAME_TF.setEditable(false);
        TRNAME_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRNAME_TFActionPerformed(evt);
            }
        });
        avail_panel.add(TRNAME_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 150, -1));

        TRNO_TF.setEditable(false);
        TRNO_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TRNO_TFActionPerformed(evt);
            }
        });
        avail_panel.add(TRNO_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, -1));

        DIST_TF.setEditable(false);
        avail_panel.add(DIST_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, -1));

        AVAIL_TF.setEditable(false);
        avail_panel.add(AVAIL_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, -1));

        jLabel10.setText("Train No");
        avail_panel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 80, 30));

        jLabel11.setText("Train Name");
        avail_panel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        AVAIL_LB.setText("Availlibility");
        avail_panel.add(AVAIL_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 80, -1));

        jLabel13.setText("Distance");
        avail_panel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));

        getContentPane().add(avail_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 80, 550, 250));

        back_btn.setFont(new java.awt.Font("Tahoma", 1, 48));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 463, 340, 150));

        trsch_panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3), "Train Schedule", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        trsch_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trsch_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        trsch_btn.setText("Click Here To Check Train Schedule");
        trsch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trsch_btnActionPerformed(evt);
            }
        });
        trsch_panel.add(trsch_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 420, 150));

        getContentPane().add(trsch_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 440, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Class_RB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_RB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_RB3ActionPerformed

    private void Class_RB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_RB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_RB4ActionPerformed

    private void Class_RB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_RB6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Class_RB6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

  String text1 ,text2;
    text1= (String) from_cb.getSelectedItem();
    text2 = (String) to_cb.getSelectedItem();


 to_cb.setSelectedItem(text1);
 from_cb.setSelectedItem(text2);

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void Class_RBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Class_RBActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_Class_RBActionPerformed

    private void submit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_btnActionPerformed
    String from=(String) from_cb.getSelectedItem();
    String to=(String) to_cb.getSelectedItem();

    if(from_cb.getSelectedIndex()==0)
    {JOptionPane.showMessageDialog(null, "Please Enter ' From 'Station Name");
     class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
        trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);
    }
        else if(to_cb.getSelectedIndex()==0)
    {JOptionPane.showMessageDialog(null, "Please Enter ' TO 'Station Name");
     class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
        trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);
        }
        else if(quota_cb.getSelectedIndex() == 0)
    {JOptionPane.showMessageDialog(null, "Please Select The Type Of Quota");
     class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
        trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);
        }
        else if(type_cb.getSelectedIndex() == 0)
    {JOptionPane.showMessageDialog(null, "Please Select Ticket Type");
        class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
        trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);
        }
 else if(dateselect.equals("")){
 JOptionPane.showMessageDialog(null, "Please Select Date");
        class_panel.setEnabled(false);
        class_panel.setVisible(false);
        TBS_panel.setEnabled(false);
        TBS_panel.setVisible(false);
        trlist_table.setVisible(false);
        trlist_table.setEnabled(false);
        avail_panel.setEnabled(false);
        avail_panel.setVisible(false);
 trsch_panel.setVisible(false);
        trsch_panel.setEnabled(false);}
    
    
 else
 {

        DefaultTableModel dm =(DefaultTableModel)trlist_table.getModel();
  int len =dm.getRowCount();
          for(int i =1;i<=len;i++){
              dm.removeRow(0);}
        String trno = null;
        String trname = null;
        String From = null ;
        String depart = null ;
        String To = null;
        String arrive = null;
        String dist = null;
        String traveltime = null;
        String Monday = null;
        String Tuesday = null;
        String Wednesday = null;
        String Thursday = null;
        String Friday = null;
        String Saturday = null;
        String Sunday = null;

    try{

 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
Statement stmt=con.createStatement();

String q = "SELECT * from trains where From_Station='"+from+"'&&To_Station='"+to+"';";
  ResultSet rs = stmt.executeQuery(q);
  while(rs.next())
{trno = rs.getString(1);
trname= rs.getString(2);
From= rs.getString(3);
depart= rs.getString(4);
To= rs.getString(5);
arrive= rs.getString(6);
dist= rs.getString(7);
traveltime=rs.getString(8);
Monday=rs.getString(9);
Tuesday=rs.getString(10);
Wednesday=rs.getString(11);
Thursday=rs.getString(12);
Friday=rs.getString(13);
Saturday=rs.getString(14);
Sunday=rs.getString(15);
  if(from.equals(From)&&to.equals(To)){
dm.addRow(new Object[]{trno,trname,From,depart,To,arrive,dist,traveltime,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday});
trlist_table.setVisible(true);
trlist_table.setEnabled(true);
class_panel.setVisible(true);
    class_panel.setEnabled(true);
  TBS_panel.setEnabled(true);
  TBS_panel.setVisible(true);
  avail_panel.setEnabled(true);
        avail_panel.setVisible(true);
        trsch_panel.setVisible(true);
        trsch_panel.setEnabled(true);
}
else{JOptionPane.showMessageDialog(null, "Please Check Station");}

  }
 }
catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}

 String contain="0123456789";
Random rnd= new Random();
StringBuilder sb = new StringBuilder(3);
for (int i=0;i<3;i++)
{sb.append(contain.charAt(rnd.nextInt(contain.length())));}
String random =sb.toString();
AVAIL_TF.setText(random);
}

 
  // TODO add your handling code here:
    }//GEN-LAST:event_submit_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
dateselect.setText("");
from_cb.setSelectedIndex(0);
to_cb.setSelectedIndex(0);
type_cb.setSelectedIndex(0);
quota_cb.setSelectedIndex(0);
class_panel.setEnabled(false);
 class_panel.setVisible(false);
 TBS_panel.setEnabled(false);
 TBS_panel.setVisible(false);
 trlist_table.setVisible(false);
 trlist_table.setEnabled(false);
 avail_panel.setEnabled(false);
 avail_panel.setVisible(false);
 trsch_panel.setVisible(false);
 trsch_panel.setEnabled(false);
// TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
home h1 =new home();
home.TF_UID.setText(this.Uid_TF.getText());
h1.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_btnActionPerformed

if(TRNAME_TF.getText().isEmpty()==false&&TRNO_TF.getText().isEmpty()==false&&DIST_TF.getText().isEmpty()==false&&Class_RB.isSelected()==true||Class_RB2.isSelected()==true||Class_RB3.isSelected()==true||Class_RB4.isSelected()==true||Class_RB5.isSelected()==true||Class_RB6.isSelected()==true)
{bookingticket a1 = new bookingticket();
bookingticket.From_TF.setText((String) this.from_cb.getSelectedItem());
bookingticket.BP_TF.setText((String) this.from_cb.getSelectedItem());
bookingticket.To_TF.setText((String) this.to_cb.getSelectedItem());
bookingticket.Upto_TF.setText((String) this.to_cb.getSelectedItem());
bookingticket.Date_TF.setText((String)this.dateselect.getText());
bookingticket.Quota_TF.setText((String) this.quota_cb.getSelectedItem());
bookingticket.Type_TF.setText((String) this.type_cb.getSelectedItem());
bookingticket.Trname_TF.setText(this.TRNAME_TF.getText());
bookingticket.Trno_TF.setText(this.TRNO_TF.getText());
bookingticket.Avail_TF.setText(this.AVAIL_TF.getText());
bookingticket.Dist_TF.setText(this.DIST_TF.getText());
bookingticket.Uid_LB.setText(this.Uid_TF.getText());
if(Class_RB.isSelected()){bookingticket.Class_TF.setText(this.Class_RB.getText());}
if(Class_RB2.isSelected()){bookingticket.Class_TF.setText(this.Class_RB2.getText());}
if(Class_RB3.isSelected()){bookingticket.Class_TF.setText(this.Class_RB3.getText());}
if(Class_RB4.isSelected()){bookingticket.Class_TF.setText(this.Class_RB4.getText());}
if(Class_RB5.isSelected()){bookingticket.Class_TF.setText(this.Class_RB5.getText());}
if(Class_RB6.isSelected()){bookingticket.Class_TF.setText(this.Class_RB6.getText());}
a1.setVisible(true);
this.setVisible(false);
}
else{JOptionPane.showMessageDialog(null, "Please Select Class/Train");
new bookingticket().setVisible(false);
this.setVisible(true);}// TODO add your handling code here:
    }//GEN-LAST:event_book_btnActionPerformed

    private void trlist_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trlist_tableMouseClicked
  int row=trlist_table.getSelectedRow();
String a =(String) trlist_table.getValueAt(row, 1);
TRNAME_TF.setText(a);
String b =(String) trlist_table.getValueAt(row, 0);
TRNO_TF.setText(b);
String c =(String) trlist_table.getValueAt(row, 6);
DIST_TF.setText(c);

// TODO add your handling code here:
    }//GEN-LAST:event_trlist_tableMouseClicked

    private void TRNAME_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRNAME_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRNAME_TFActionPerformed

    private void TRNO_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TRNO_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TRNO_TFActionPerformed

    private void trsch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trsch_btnActionPerformed
   if(TRNO_TF.getText().equals("12915")){new ashramexpress_schedule().setVisible(true);}
   else if(TRNO_TF.getText().equals("12957"))
        {
            new swarnjrajexp_schedule().setVisible(true);
        }
  else if(TRNO_TF.getText().equals("19031"))
        {
            new haridwarmail_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("12934"))
        {
            new karnavati_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("12010"))
        {
            new shatabdi_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("12932"))
        {
            new doubledecker_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("22960"))
        {
            new intercity_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("19018"))
        {
            new saujan_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("22946"))
        {
            new saumail_schedule().setVisible(true);
        }
   else if(TRNO_TF.getText().equals("19216"))
        {
            new sauexp_schedule().setVisible(true);
        }
 else{JOptionPane.showMessageDialog(null, "Please Select A Train To View Schedule");}// TODO add your handling code here:
    }//GEN-LAST:event_trsch_btnActionPerformed

    private void to_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to_cbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to_cbActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new irctcbookingsearch().setVisible(true);
            }
        });
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AVAIL_LB;
    private javax.swing.JTextField AVAIL_TF;
    private javax.swing.JRadioButton Class_RB;
    private javax.swing.JRadioButton Class_RB2;
    private javax.swing.JRadioButton Class_RB3;
    private javax.swing.JRadioButton Class_RB4;
    private javax.swing.JRadioButton Class_RB5;
    private javax.swing.JRadioButton Class_RB6;
    private javax.swing.JTextField DIST_TF;
    private javax.swing.JPanel TBS_panel;
    private javax.swing.JTextField TRNAME_TF;
    private javax.swing.JTextField TRNO_TF;
    public static javax.swing.JLabel Uid_TF;
    private javax.swing.JPanel avail_panel;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton book_btn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel class_panel;
    private datechooser.beans.DateChooserCombo dateselect;
    private javax.swing.JComboBox from_cb;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox quota_cb;
    private javax.swing.JButton reset_btn;
    private javax.swing.JButton submit_btn;
    private javax.swing.JComboBox to_cb;
    private javax.swing.JTable trlist_table;
    private javax.swing.JButton trsch_btn;
    private javax.swing.JPanel trsch_panel;
    private javax.swing.JComboBox type_cb;
    // End of variables declaration//GEN-END:variables

}
