
import java.awt.Color;
import java.sql.* ;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mhexpcanceljourney.java
 *
 * Created on May 31, 2017, 5:10:56 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class mhexpcanceljourney extends javax.swing.JFrame {

    /** Creates new form mhexpcanceljourney */
    public mhexpcanceljourney() {
        initComponents(); getContentPane().setBackground(new Color(0,51,102));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pnr_txt = new javax.swing.JTextField();
        captcha_txt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel_btn = new javax.swing.JButton();
        clr_btn = new javax.swing.JButton();
        Cap_LB = new javax.swing.JLabel();
        captcha_btn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 70, 210, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 180, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 1330, 130));

        jLabel5.setBackground(new java.awt.Color(153, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cancel Maharajas' Express Journey");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 670, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnr_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnr_txtActionPerformed(evt);
            }
        });
        jPanel1.add(pnr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 140, -1));
        jPanel1.add(captcha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 3, 14));
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("( Letters are case sensitive. )");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PNR");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 50, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Captcha");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel Journey");
        cancel_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, -1, -1));

        clr_btn.setBackground(new java.awt.Color(0, 255, 0));
        clr_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        clr_btn.setForeground(new java.awt.Color(255, 255, 255));
        clr_btn.setText("Clear");
        clr_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        clr_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clr_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        Cap_LB.setFont(new java.awt.Font("Times New Roman", 3, 36));
        Cap_LB.setForeground(new java.awt.Color(255, 0, 0));
        Cap_LB.setText("HJB518AL");
        jPanel1.add(Cap_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 180, 40));

        captcha_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ref.jpg"))); // NOI18N
        captcha_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captcha_btnActionPerformed(evt);
            }
        });
        jPanel1.add(captcha_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 20, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recaptcha-edited.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 100, 40));

        back_btn.setBackground(new java.awt.Color(0, 255, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 24));
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sQ05dJt.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 620, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
String pnr=pnr_txt.getText();
String Captcha=captcha_txt.getText();
        
        try
{
 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt=con.createStatement();
 String q= "Delete from  maharajas_express where PNR ='"+pnr+"';";

  
 if(Captcha.equals(Cap_LB.getText()))
 {JOptionPane.showMessageDialog(this, "Journey Cancelled");
  stmt.executeUpdate(q);
  pnr_txt.setText("");
captcha_txt.setText("");
String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(8);
        for (int i=0;i<8;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        Cap_LB.setText(random);
 }
 else if(!Captcha.equals(Cap_LB.getText()))
 {
 JOptionPane.showMessageDialog(this, "Please Check Captcha OR PNR Number");
 }
}
        catch (Exception e)
        {
JOptionPane.showMessageDialog(null, e.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void pnr_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnr_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnr_txtActionPerformed

    private void clr_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_btnActionPerformed
pnr_txt.setText("");
captcha_txt.setText("");
String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(8);
        for (int i=0;i<8;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        Cap_LB.setText(random);// TODO add your handling code here:
    }//GEN-LAST:event_clr_btnActionPerformed

    private void captcha_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captcha_btnActionPerformed
        String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(8);
        for (int i=0;i<8;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        Cap_LB.setText(random);// TODO add your handling code here:
}//GEN-LAST:event_captcha_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
this.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mhexpcanceljourney().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cap_LB;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton captcha_btn;
    private javax.swing.JTextField captcha_txt;
    private javax.swing.JButton clr_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pnr_txt;
    // End of variables declaration//GEN-END:variables

}
