
import java.awt.Color;import java.sql.* ;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mhexpreservation.java
 *
 * Created on May 29, 2017, 11:42:07 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class mhexpreservation extends javax.swing.JFrame {

    /** Creates new form mhexpreservation */
    public mhexpreservation() {
        initComponents();
        PNR_TF.setVisible(false);
        jLabel37.setVisible(false);
        String contain="0123456789";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(10);
        for (int i=0;i<10;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        PNR_TF.setText(random);
        getContentPane().setBackground(new Color(0,51,102));
    Age_txt2.setEnabled(false); Name_txt2.setEnabled(false); Sex_cb2.setEnabled(false); jLabel15.setEnabled(false);jButton6.setEnabled(false);
Age_txt2.setVisible(false); Name_txt2.setVisible(false); Sex_cb2.setVisible(false); jLabel15.setVisible(false);jButton6.setVisible(false);
  Age_txt1.setEnabled(false); Sex_cb1.setEnabled(false); Name_txt1.setEnabled(false); jLabel14.setEnabled(false); jButton8.setEnabled(false);
Age_txt1.setVisible(false); Sex_cb1.setVisible(false); Name_txt1.setVisible(false); jLabel14.setVisible(false);jButton8.setVisible(false);
Sex_cb3.setEnabled(false); Name_txt3.setEnabled(false); Age_txt3.setEnabled(false); jLabel16.setEnabled(false); jButton5.setEnabled(false);
Sex_cb3.setVisible(false); Name_txt3.setVisible(false); Age_txt3.setVisible(false); jLabel16.setVisible(false); jButton5.setVisible(false);//
 Age_txt4.setEnabled(false); Name_txt4.setEnabled(false) ;jLabel17.setEnabled(false); Sex_cb4.setEnabled(false);jButton4.setEnabled(false);
Age_txt4.setVisible(false); Name_txt4.setVisible(false) ;jLabel17.setVisible(false); Sex_cb4.setVisible(false);jButton4.setVisible(false);
Sex_cb5.setEnabled(false); Name_txt5.setEnabled(false); jLabel18.setEnabled(false);Age_txt5.setEnabled(false);jButton3.setEnabled(false);
Sex_cb5.setVisible(false); Name_txt5.setVisible(false); jLabel18.setVisible(false);Age_txt5.setVisible(false); jButton3.setVisible(false);
   name_txt1.setEnabled(false); jButton14.setEnabled(false); jButton11.setEnabled(false); name_txt2.setEnabled(false); jButton12.setEnabled(false); name_txt4.setEnabled(false); age_txt2.setEnabled(false); sex_cb4.setEnabled(false); jButton9.setEnabled(false); jButton10.setEnabled(false);  jLabel25.setEnabled(false); jLabel24.setEnabled(false); sex_cb2.setEnabled(false); sex_cb3.setEnabled(false); age_txt3.setEnabled(false); age_txt5.setEnabled(false); name_txt5.setEnabled(false); sex_cb1.setEnabled(false); jLabel27.setEnabled(false); age_txt1.setEnabled(false); sex_cb5.setEnabled(false); jLabel28.setEnabled(false); jLabel29.setEnabled(false); age_txt4.setEnabled(false);
  name_txt1.setVisible(false); jButton14.setVisible(false); jButton11.setVisible(false); name_txt2.setVisible(false); jButton12.setVisible(false); name_txt4.setVisible(false); age_txt2.setVisible(false); sex_cb4.setVisible(false); jButton9.setVisible(false); jButton10.setVisible(false);  jLabel25.setVisible(false); jLabel24.setVisible(false); sex_cb2.setVisible(false); sex_cb3.setVisible(false); age_txt3.setVisible(false); age_txt5.setVisible(false); name_txt5.setVisible(false); sex_cb1.setVisible(false); jLabel27.setVisible(false); age_txt1.setVisible(false); sex_cb5.setVisible(false); jLabel28.setVisible(false); jLabel29.setVisible(false); age_txt4.setVisible(false);
  name_txt3.setVisible(false); name_txt3.setEnabled(false); jButton9.setEnabled(false);jButton9.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        journey_cb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        PNR_TF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Name_txt = new javax.swing.JTextField();
        Name_txt1 = new javax.swing.JTextField();
        Name_txt3 = new javax.swing.JTextField();
        Name_txt2 = new javax.swing.JTextField();
        Name_txt4 = new javax.swing.JTextField();
        Name_txt5 = new javax.swing.JTextField();
        Age_txt = new javax.swing.JTextField();
        Age_txt1 = new javax.swing.JTextField();
        Age_txt2 = new javax.swing.JTextField();
        Age_txt3 = new javax.swing.JTextField();
        Age_txt4 = new javax.swing.JTextField();
        Age_txt5 = new javax.swing.JTextField();
        Sex_cb = new javax.swing.JComboBox();
        Sex_cb1 = new javax.swing.JComboBox();
        Sex_cb2 = new javax.swing.JComboBox();
        Sex_cb3 = new javax.swing.JComboBox();
        Sex_cb4 = new javax.swing.JComboBox();
        Sex_cb5 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        sex_cb = new javax.swing.JComboBox();
        sex_cb1 = new javax.swing.JComboBox();
        sex_cb2 = new javax.swing.JComboBox();
        sex_cb3 = new javax.swing.JComboBox();
        sex_cb4 = new javax.swing.JComboBox();
        sex_cb5 = new javax.swing.JComboBox();
        age_txt1 = new javax.swing.JTextField();
        age_txt = new javax.swing.JTextField();
        age_txt2 = new javax.swing.JTextField();
        age_txt3 = new javax.swing.JTextField();
        age_txt5 = new javax.swing.JTextField();
        age_txt4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        name_txt3 = new javax.swing.JTextField();
        name_txt1 = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        name_txt5 = new javax.swing.JTextField();
        name_txt2 = new javax.swing.JTextField();
        name_txt4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        MoNo_txt = new javax.swing.JTextField();
        email_txt = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        tnc_c = new javax.swing.JCheckBox();
        Captcha_LB = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        captcha_txt = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        reset_btn = new javax.swing.JButton();
        Book_btn = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        captcha_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 70, 200, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, -10, 1290, 140));

        jLabel4.setBackground(new java.awt.Color(153, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 36));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Maharajas' Express Reservation");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0), 3));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 600, 70));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        journey_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Journey:-", "Heritage of India Journey", "Treasures of India Journey", "Gems of India Journey", "Indian Panorama Journey", "Indian Splendor Journey", "The Southern Jewels (New)", "The Southern Sojourn (New)" }));
        jPanel1.add(journey_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel5.setText("Select Tour");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        PNR_TF.setEditable(false);
        jPanel1.add(PNR_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel7.setText("Passenger Details");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel9.setText("SNO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel10.setText("NAME");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel11.setText("AGE");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel12.setText("SEX");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, -1));

        jLabel13.setText("1.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel14.setText("2.");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 21, -1));

        jLabel15.setText("3.");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel16.setText("4.");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel17.setText("5.");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel18.setText("6.");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        Name_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(Name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 90, -1));

        Name_txt1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(Name_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 90, -1));

        Name_txt3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Name_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_txt3ActionPerformed(evt);
            }
        });
        jPanel1.add(Name_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 90, -1));

        Name_txt2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Name_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_txt2ActionPerformed(evt);
            }
        });
        jPanel1.add(Name_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 90, -1));

        Name_txt4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(Name_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 90, -1));

        Name_txt5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Name_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_txt5ActionPerformed(evt);
            }
        });
        jPanel1.add(Name_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 90, -1));

        Age_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txtActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 93, -1));

        Age_txt1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 93, -1));

        Age_txt2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txt2ActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 93, -1));

        Age_txt3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txt3ActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 93, -1));

        Age_txt4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txt4ActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 93, -1));

        Age_txt5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        Age_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Age_txt5ActionPerformed(evt);
            }
        });
        jPanel1.add(Age_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 93, -1));

        Sex_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        Sex_cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, -1, -1));

        Sex_cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        Sex_cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 290, -1, -1));

        Sex_cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex ", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        Sex_cb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(Sex_cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 18));
        jLabel19.setText("Child Passenger Details");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel20.setText("SNO");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel21.setText("NAME");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel23.setText("AGE");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel22.setText("SEX");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, -1));

        sex_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        sex_cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 480, -1, -1));

        sex_cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));

        sex_cb3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, -1, -1));

        sex_cb4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        sex_cb5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Sex", "MALE", "FEMALE", "TRANSGENDER" }));
        jPanel1.add(sex_cb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 600, -1, -1));

        age_txt1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txt1ActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 93, -1));

        age_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txtActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 93, -1));

        age_txt2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txt2ActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 93, -1));

        age_txt3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txt3ActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 93, -1));

        age_txt5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txt5ActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 600, 93, -1));

        age_txt4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        age_txt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                age_txt4ActionPerformed(evt);
            }
        });
        jPanel1.add(age_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 93, -1));

        jLabel24.setText("6.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 600, -1, -1));

        jLabel25.setText("5.");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, -1, -1));

        jLabel26.setText("1.");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 21, -1));

        jLabel27.setText("2.");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 480, 21, -1));

        jLabel28.setText("3.");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        jLabel29.setText("4.");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        name_txt3.setFont(new java.awt.Font("Times New Roman", 0, 14));
        name_txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt3ActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 90, 20));

        name_txt1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(name_txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 90, -1));

        name_txt.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        name_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txtActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 90, -1));

        name_txt5.setFont(new java.awt.Font("Times New Roman", 0, 14));
        name_txt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt5ActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 90, -1));

        name_txt2.setFont(new java.awt.Font("Times New Roman", 0, 14));
        name_txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_txt2ActionPerformed(evt);
            }
        });
        jPanel1.add(name_txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 90, -1));

        name_txt4.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(name_txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 90, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel30.setText("Mobile Number");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel31.setText("Email Id");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, -1, -1));

        MoNo_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(MoNo_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 260, -1));

        email_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(email_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 690, 260, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel32.setForeground(new java.awt.Color(255, 0, 0));
        jLabel32.setText("( E-Ticket ,PNR and passenger details would be sent to this Email Id. )");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel33.setForeground(new java.awt.Color(255, 0, 0));
        jLabel33.setText("( E-Ticket ,PNR and passenger details would be sent to this number. )");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, -1));

        tnc_c.setText("I agree the terms and conditions of IRCTC");
        jPanel1.add(tnc_c, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 810, -1, -1));

        Captcha_LB.setFont(new java.awt.Font("Times New Roman", 1, 24));
        Captcha_LB.setText("PDbceM8P");
        jPanel1.add(Captcha_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 750, 140, 50));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel35.setText("Captcha");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 730, -1, -1));

        captcha_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(captcha_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 730, 260, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel36.setForeground(new java.awt.Color(255, 0, 0));
        jLabel36.setText("( Letters are case sensitive. )");
        jPanel1.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 730, -1, -1));

        reset_btn.setBackground(new java.awt.Color(255, 0, 51));
        reset_btn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        reset_btn.setForeground(new java.awt.Color(255, 255, 255));
        reset_btn.setText("Reset");
        reset_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_btnActionPerformed(evt);
            }
        });
        jPanel1.add(reset_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 850, -1, -1));

        Book_btn.setBackground(new java.awt.Color(0, 255, 0));
        Book_btn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        Book_btn.setForeground(new java.awt.Color(255, 255, 255));
        Book_btn.setText("Book");
        Book_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Book_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Book_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 850, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel37.setText("PNR");
        jPanel1.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton3.setText("One");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, -1, -1));

        jButton4.setText("Add");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, -1, -1));

        jButton5.setText("Add");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, -1));

        jButton7.setText("Add");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        jButton8.setText("Add");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, -1, -1));

        jButton9.setText("One");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, -1, -1));

        jButton10.setText("Add");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 570, -1, -1));

        jButton11.setText("Add");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, -1, -1));

        jButton12.setText("Add");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, -1, -1));

        jButton13.setText("Add");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, -1, -1));

        jButton14.setText("Add");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, -1, -1));

        captcha_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ref.jpg"))); // NOI18N
        captcha_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                captcha_btnActionPerformed(evt);
            }
        });
        jPanel1.add(captcha_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 760, 30, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/recaptcha-edited.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 760, 100, 30));

        back_btn.setBackground(new java.awt.Color(255, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 14));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 850, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 920, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Name_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_txt3ActionPerformed

    private void Name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_txtActionPerformed

    private void Name_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_txt2ActionPerformed

    private void Name_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_txt5ActionPerformed

    private void Age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txtActionPerformed

    private void Age_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txt1ActionPerformed

    private void Age_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txt2ActionPerformed

    private void Age_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txt3ActionPerformed

    private void Age_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txt4ActionPerformed

    private void Age_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Age_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Age_txt5ActionPerformed

    private void age_txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txt1ActionPerformed

    private void age_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txtActionPerformed

    private void age_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txt2ActionPerformed

    private void age_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txt3ActionPerformed

    private void age_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txt5ActionPerformed

    private void age_txt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_age_txt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_age_txt4ActionPerformed

    private void name_txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt3ActionPerformed

    private void name_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txtActionPerformed

    private void name_txt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt5ActionPerformed

    private void name_txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_txt2ActionPerformed

    private void Book_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Book_btnActionPerformed
String PNR=PNR_TF.getText();
String name=Name_txt.getText();
String name1=Name_txt1.getText();
String name2=Name_txt3.getText();
String name3=Name_txt2.getText();
String name4=Name_txt4.getText();
String name5=Name_txt5.getText();
String age=Age_txt.getText();
String age1=Age_txt1.getText();
String age2=Age_txt2.getText();
String age3=Age_txt3.getText();
String age4=Age_txt4.getText();
String age5=Age_txt5.getText();
String sex=(String) Sex_cb.getSelectedItem();
String sex1=(String) Sex_cb1.getSelectedItem();
String sex2=(String) Sex_cb2.getSelectedItem();
String sex3=(String) Sex_cb3.getSelectedItem();
String sex4=(String) Sex_cb4.getSelectedItem();
String sex5=(String) Sex_cb5.getSelectedItem();

String tour = journey_cb.getSelectedItem().toString();


String Name=name_txt.getText();
String Name1=name_txt1.getText();
String Name2=name_txt2.getText();
String Name3=name_txt3.getText();
String Name4=name_txt4.getText();
String Name5=name_txt5.getText();
String Age=age_txt.getText();
String Age1=age_txt1.getText();
String Age2=age_txt2.getText();
String Age3=age_txt3.getText();
String Age4=age_txt4.getText();
String Age5=age_txt5.getText();
String Sex=(String) sex_cb.getSelectedItem();
String Sex1=(String) sex_cb1.getSelectedItem();
String Sex2=(String) sex_cb2.getSelectedItem();
String Sex3=(String) sex_cb3.getSelectedItem();
String Sex4=(String) sex_cb4.getSelectedItem();
String Sex5=(String) sex_cb5.getSelectedItem();

        String  mobile =MoNo_txt.getText();
        String email = email_txt.getText();

try
{
    Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 String q= "Insert into maharajas_express (PNR,Tour,Name,Age,Sex,Name1,Age1,Sex1,Mobile_No,Email_Id) values (?,?,?,?,?,?,?,?,?,?)";

PreparedStatement stmt = con.prepareStatement(q);
if (journey_cb.getSelectedIndex()==0||Sex_cb.getSelectedIndex()==0||MoNo_txt.getText().length()<=0 ||email_txt.getText().length()<=0||tnc_c.isSelected()==false||Age_txt.getText().length()<=0||Name_txt.getText().length()<=0||!captcha_txt.getText().equals(Captcha_LB.getText())||MoNo_txt.getText().length()>10 )
            {
stmt.setString(1, null);
 stmt.setString(2,null);
 stmt.setString(3,null);
 stmt.setString(4,null);
 stmt.setString(5,null);
 stmt.setString(6,null);
 stmt.setString(7,null);
 stmt.setString(8,null);
 stmt.setString(9,null);
 stmt.setString(10,null);
 JOptionPane.showMessageDialog(null, "Booking Unsucessfull - Please Fill all the details OR Please Select Your Journey.");
            }
else if (captcha_txt.getText().equals(Captcha_LB.getText())&&Name_txt.getText().length()>0 || Age_txt.getText().length()>0||Sex_cb.getSelectedIndex()>0 )
{
 stmt.setString(1, PNR);
 stmt.setString(2,tour);
 stmt.setString(3,name+" "+name1+" "+name2+" "+name3+" "+name4+" "+name5);
 stmt.setString(4,age+" "+age1+" "+age2+" "+age3+" "+age4+" "+age5);
 stmt.setString(5,sex+" "+sex1+" "+sex2+" "+sex3+" "+sex4+" "+sex5);
 stmt.setString(6,Name+" "+Name1+" "+Name2+" "+Name3+" "+Name4+" "+Name5);
  stmt.setString(7,Age+" "+Age1+" "+Age2+" "+Age3+" "+Age4+" "+Age5);
   stmt.setString(8,Sex+" "+Sex1+" "+Sex2+" "+Sex3+" "+Sex4+" "+Sex5);
   stmt.setString(9,mobile);
   stmt.setString(10,email);
 stmt.execute();
 stmt.close();
 JOptionPane.showMessageDialog(null, "Booking Done Sucessfully !!");}
 
 }

catch (Exception e)
{
JOptionPane.showMessageDialog(null, e.getMessage());
}// TODO add your handling code here:
    }//GEN-LAST:event_Book_btnActionPerformed

    private void reset_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_btnActionPerformed
tnc_c.setSelected(false);
     Name_txt.setText("");
     Name_txt1.setText("");
     Name_txt3.setText("");
     Name_txt2.setText("");
     Name_txt4.setText("");
     Name_txt5.setText("");
     Age_txt.setText("");
     Age_txt1.setText("");
     Age_txt2.setText("");
     Age_txt3.setText("");
     Age_txt4.setText("");
     Age_txt5.setText("");
     age_txt1.setText("");
     age_txt.setText("");
     age_txt2.setText("");
     age_txt3.setText("");
     age_txt5.setText("");
     age_txt4.setText("");
     name_txt3.setText("");
     name_txt1.setText("");
     name_txt.setText("");
     name_txt5.setText("");
     name_txt2.setText("");
     name_txt4.setText("");
     MoNo_txt.setText("");
     email_txt.setText("");
     captcha_txt.setText("");
     // TODO add your handling code here:
    }//GEN-LAST:event_reset_btnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
jButton8.setEnabled(false);jButton8.setVisible(false);Age_txt2.setEnabled(true); Name_txt2.setEnabled(true); Sex_cb2.setEnabled(true); jLabel15.setEnabled(true);jButton6.setEnabled(true);
Age_txt2.setVisible(true); Name_txt2.setVisible(true); Sex_cb2.setVisible(true); jLabel15.setVisible(true);jButton6.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
age_txt2.setEnabled(true); sex_cb2.setEnabled(true); jLabel28.setEnabled(true); name_txt2.setEnabled(true); jButton12.setEnabled(true);
age_txt2.setVisible(true); sex_cb2.setVisible(true); jLabel28.setVisible(true); name_txt2.setVisible(true); jButton12.setVisible(true);
jButton14.setEnabled(false);jButton14.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
jButton7.setEnabled(false);jButton7.setVisible(false);Age_txt1.setEnabled(true); Sex_cb1.setEnabled(true); Name_txt1.setEnabled(true); jLabel14.setEnabled(true); jButton8.setEnabled(true);
Age_txt1.setVisible(true); Sex_cb1.setVisible(true); Name_txt1.setVisible(true); jLabel14.setVisible(true);jButton8.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
jButton6.setEnabled(false);jButton6.setVisible(false);Sex_cb3.setEnabled(true); Name_txt3.setEnabled(true); Age_txt3.setEnabled(true); jLabel16.setEnabled(true); jButton5.setEnabled(true);
Sex_cb3.setVisible(true); Name_txt3.setVisible(true); Age_txt3.setVisible(true); jLabel16.setVisible(true); jButton5.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
jButton5.setEnabled(false);jButton5.setVisible(false);Age_txt4.setEnabled(true); Name_txt4.setEnabled(true) ;jLabel17.setEnabled(true); Sex_cb4.setEnabled(true);jButton4.setEnabled(true);
Age_txt4.setVisible(true); Name_txt4.setVisible(true) ;jLabel17.setVisible(true); Sex_cb4.setVisible(true);jButton4.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
jButton4.setVisible(false);jButton4.setEnabled(false);Sex_cb5.setEnabled(true); Name_txt5.setEnabled(true); jLabel18.setEnabled(true);Age_txt5.setEnabled(true);jButton3.setEnabled(true);
Sex_cb5.setVisible(true); Name_txt5.setVisible(true); jLabel18.setVisible(true);Age_txt5.setVisible(true); jButton3.setVisible(true);       //// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Age_txt2.setEnabled(false); Name_txt2.setEnabled(false); Sex_cb2.setEnabled(false); jLabel15.setEnabled(false);jButton6.setEnabled(false);
Age_txt2.setVisible(false); Name_txt2.setVisible(false); Sex_cb2.setVisible(false); jLabel15.setVisible(false);jButton6.setVisible(false);
  Age_txt1.setEnabled(false); Sex_cb1.setEnabled(false); Name_txt1.setEnabled(false); jLabel14.setEnabled(false); jButton8.setEnabled(false);
Age_txt1.setVisible(false); Sex_cb1.setVisible(false); Name_txt1.setVisible(false); jLabel14.setVisible(false);jButton8.setVisible(false);
Sex_cb3.setEnabled(false); Name_txt3.setEnabled(false); Age_txt3.setEnabled(false); jLabel16.setEnabled(false); jButton5.setEnabled(false);
Sex_cb3.setVisible(false); Name_txt3.setVisible(false); Age_txt3.setVisible(false); jLabel16.setVisible(false); jButton5.setVisible(false);//
 Age_txt4.setEnabled(false); Name_txt4.setEnabled(false) ;jLabel17.setEnabled(false); Sex_cb4.setEnabled(false);jButton4.setEnabled(false);
Age_txt4.setVisible(false); Name_txt4.setVisible(false) ;jLabel17.setVisible(false); Sex_cb4.setVisible(false);jButton4.setVisible(false);

Sex_cb5.setEnabled(false); Name_txt5.setEnabled(false); jLabel18.setEnabled(false);Age_txt5.setEnabled(false);jButton3.setEnabled(false);
Sex_cb5.setVisible(false); Name_txt5.setVisible(false); jLabel18.setVisible(false);Age_txt5.setVisible(false); jButton3.setVisible(false);
jButton3.setEnabled(false);jButton3.setVisible(false);Sex_cb.setEnabled(true); Age_txt.setEnabled(true); jButton7.setEnabled(true); jLabel13.setEnabled(true); Name_txt.setEnabled(true);
Sex_cb.setVisible(true); Age_txt.setVisible(true); jButton7.setVisible(true); jLabel13.setVisible(true); Name_txt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
name_txt1.setEnabled(false); jButton14.setEnabled(false); jButton11.setEnabled(false); name_txt2.setEnabled(false); jButton12.setEnabled(false); name_txt4.setEnabled(false); age_txt2.setEnabled(false); sex_cb4.setEnabled(false); jButton9.setEnabled(false); jButton10.setEnabled(false);  jLabel25.setEnabled(false); jLabel24.setEnabled(false); sex_cb2.setEnabled(false); sex_cb3.setEnabled(false); age_txt3.setEnabled(false); age_txt5.setEnabled(false); name_txt5.setEnabled(false); sex_cb1.setEnabled(false); jLabel27.setEnabled(false); age_txt1.setEnabled(false); sex_cb5.setEnabled(false); jLabel28.setEnabled(false); jLabel29.setEnabled(false); age_txt4.setEnabled(false);
  name_txt1.setVisible(false); jButton14.setVisible(false); jButton11.setVisible(false); name_txt2.setVisible(false); jButton12.setVisible(false); name_txt4.setVisible(false); age_txt2.setVisible(false); sex_cb4.setVisible(false); jButton9.setVisible(false); jButton10.setVisible(false);  jLabel25.setVisible(false); jLabel24.setVisible(false); sex_cb2.setVisible(false); sex_cb3.setVisible(false); age_txt3.setVisible(false); age_txt5.setVisible(false); name_txt5.setVisible(false); sex_cb1.setVisible(false); jLabel27.setVisible(false); age_txt1.setVisible(false); sex_cb5.setVisible(false); jLabel28.setVisible(false); jLabel29.setVisible(false); age_txt4.setVisible(false);
  name_txt3.setVisible(false); name_txt3.setEnabled(false); jButton9.setEnabled(false);jButton9.setVisible(false);
  sex_cb.setEnabled(true); jLabel26.setEnabled(true); name_txt.setEnabled(true); jButton13.setEnabled(true); age_txt.setEnabled(true);
  sex_cb.setVisible(true); jLabel26.setVisible(true); name_txt.setVisible(true); jButton13.setVisible(true); age_txt.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
name_txt1.setEnabled(true); sex_cb1.setEnabled(true); jLabel27.setEnabled(true); age_txt1.setEnabled(true);
name_txt1.setVisible(true); sex_cb1.setVisible(true); jLabel27.setVisible(true); age_txt1.setVisible(true);jButton14.setVisible(true);jButton14.setEnabled(true);
jButton13.setEnabled(false);jButton13.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
name_txt3.setEnabled(true); sex_cb3.setEnabled(true); age_txt3.setEnabled(true); jButton11.setEnabled(true); jLabel29.setEnabled(true);
name_txt3.setVisible(true); sex_cb3.setVisible(true); age_txt3.setVisible(true); jButton11.setVisible(true); jLabel29.setVisible(true);
jButton12.setEnabled(false);jButton12.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
name_txt4.setEnabled(true); sex_cb4.setEnabled(true); jLabel25.setEnabled(true); jButton10.setEnabled(true); age_txt4.setEnabled(true);
name_txt4.setVisible(true); sex_cb4.setVisible(true); jLabel25.setVisible(true); jButton10.setVisible(true); age_txt4.setVisible(true);
jButton11.setEnabled(false);jButton11.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
sex_cb5.setEnabled(true); jButton9.setEnabled(true); jLabel24.setEnabled(true); age_txt5.setEnabled(true); name_txt5.setEnabled(true);
sex_cb5.setVisible(true); jButton9.setVisible(true); jLabel24.setVisible(true); age_txt5.setVisible(true); name_txt5.setVisible(true);jButton10.setEnabled(false);jButton10.setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void captcha_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_captcha_btnActionPerformed
String contain="0123456789ABCDEFGHIJKLMONPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
        Random rnd= new Random();
        StringBuilder sb = new StringBuilder(8);
        for (int i=0;i<8;i++) {
            sb.append(contain.charAt(rnd.nextInt(contain.length())));}
        String random =sb.toString();
        Captcha_LB.setText(random);        // TODO add your handling code here:
    }//GEN-LAST:event_captcha_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mhexpreservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age_txt;
    private javax.swing.JTextField Age_txt1;
    private javax.swing.JTextField Age_txt2;
    private javax.swing.JTextField Age_txt3;
    private javax.swing.JTextField Age_txt4;
    private javax.swing.JTextField Age_txt5;
    private javax.swing.JButton Book_btn;
    private javax.swing.JLabel Captcha_LB;
    private javax.swing.JTextField MoNo_txt;
    private javax.swing.JTextField Name_txt;
    private javax.swing.JTextField Name_txt1;
    private javax.swing.JTextField Name_txt2;
    private javax.swing.JTextField Name_txt3;
    private javax.swing.JTextField Name_txt4;
    private javax.swing.JTextField Name_txt5;
    private javax.swing.JTextField PNR_TF;
    private javax.swing.JComboBox Sex_cb;
    private javax.swing.JComboBox Sex_cb1;
    private javax.swing.JComboBox Sex_cb2;
    private javax.swing.JComboBox Sex_cb3;
    private javax.swing.JComboBox Sex_cb4;
    private javax.swing.JComboBox Sex_cb5;
    private javax.swing.JTextField age_txt;
    private javax.swing.JTextField age_txt1;
    private javax.swing.JTextField age_txt2;
    private javax.swing.JTextField age_txt3;
    private javax.swing.JTextField age_txt4;
    private javax.swing.JTextField age_txt5;
    private javax.swing.JButton back_btn;
    private javax.swing.JButton captcha_btn;
    private javax.swing.JTextField captcha_txt;
    private javax.swing.JTextField email_txt;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox journey_cb;
    private javax.swing.JTextField name_txt;
    private javax.swing.JTextField name_txt1;
    private javax.swing.JTextField name_txt2;
    private javax.swing.JTextField name_txt3;
    private javax.swing.JTextField name_txt4;
    private javax.swing.JTextField name_txt5;
    private javax.swing.JButton reset_btn;
    private javax.swing.JComboBox sex_cb;
    private javax.swing.JComboBox sex_cb1;
    private javax.swing.JComboBox sex_cb2;
    private javax.swing.JComboBox sex_cb3;
    private javax.swing.JComboBox sex_cb4;
    private javax.swing.JComboBox sex_cb5;
    private javax.swing.JCheckBox tnc_c;
    // End of variables declaration//GEN-END:variables

}
