
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;




/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mhrexpawrds.java
 *
 * Created on May 23, 2017, 1:07:21 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class mhrexpawrds extends javax.swing.JFrame {

    /** Creates new form mhrexpawrds */
    public mhrexpawrds() {
        initComponents();getContentPane().setBackground(new Color(0,51,102));
      jTextArea1.setText("Winner of the Seven Stars 2016 in the category 'Luxury Hospitality and Life style Awards'");
jTextArea2.setText("Coveted winner of World Travel Award 2015 in the category of 'World's Leading Luxury Train'");
jTextArea3.setText("Winner of the Seven Stars 2015 in the category 'Luxury Hospitality and Life style Awards'");
jTextArea9.setText("Coveted winner of World Travel Award 2016 in the category of 'World's Leading Luxury Train'");
jTextArea4.setText("Coveted winner of World Travel Award 2014 in the category of 'World's Leading Luxury Train'");
jTextArea5.setText("Coveted winner of World Travel Award 2013 in the category of 'World's Leading Luxury Train'");
jTextArea6.setText("Coveted winner of World Travel Award 2012 in the category of 'World's Leading Luxury Train'");
jTextArea7.setText("1st runner up prize in the Specialist Train Operators Category awarded at Conde Nast Traveler Readers' Travel Award 2011");
   jTextArea8.setText("Adjudged the 'Best Luxury Train' at CNBC Awaaz Travel Award 2010");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("Awards & Accolades");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea1.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 170, 140));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/seven-star-award-2015.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/worldtravelaward.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 150, -1, 140));

        jTextArea2.setColumns(20);
        jTextArea2.setEditable(false);
        jTextArea2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea2.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 180, 140));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/seven-star-award-2015.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 154, 140));

        jTextArea3.setColumns(20);
        jTextArea3.setEditable(false);
        jTextArea3.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea3.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setWrapStyleWord(true);
        jScrollPane3.setViewportView(jTextArea3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 168, 140));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 80, 200, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 80, 170, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/Mhexp.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 140));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/award-2014.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 150, 140));

        jTextArea4.setColumns(20);
        jTextArea4.setEditable(false);
        jTextArea4.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea4.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jScrollPane4.setViewportView(jTextArea4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 180, 140));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/world-travel-2013.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 320, 150, 130));

        jTextArea5.setColumns(20);
        jTextArea5.setEditable(false);
        jTextArea5.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea5.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea5.setLineWrap(true);
        jTextArea5.setRows(5);
        jTextArea5.setWrapStyleWord(true);
        jScrollPane5.setViewportView(jTextArea5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 170, 130));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/world-travel-2012.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, 140, 130));

        jTextArea6.setColumns(20);
        jTextArea6.setEditable(false);
        jTextArea6.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea6.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea6.setLineWrap(true);
        jTextArea6.setRows(5);
        jTextArea6.setWrapStyleWord(true);
        jScrollPane6.setViewportView(jTextArea6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 170, 130));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/travel-2011.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 140, 130));

        jTextArea7.setColumns(20);
        jTextArea7.setEditable(false);
        jTextArea7.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea7.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea7.setLineWrap(true);
        jTextArea7.setRows(5);
        jTextArea7.setWrapStyleWord(true);
        jScrollPane7.setViewportView(jTextArea7);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 510, 200, 140));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/cnbc.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 510, 160, 140));

        jTextArea8.setColumns(20);
        jTextArea8.setEditable(false);
        jTextArea8.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea8.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea8.setLineWrap(true);
        jTextArea8.setRows(5);
        jTextArea8.setWrapStyleWord(true);
        jScrollPane8.setViewportView(jTextArea8);

        getContentPane().add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 510, 166, 140));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Maharajas Express Image/l_3037361.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 150, 140));

        jTextArea9.setColumns(20);
        jTextArea9.setEditable(false);
        jTextArea9.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jTextArea9.setForeground(new java.awt.Color(153, 0, 0));
        jTextArea9.setLineWrap(true);
        jTextArea9.setRows(5);
        jTextArea9.setWrapStyleWord(true);
        jScrollPane9.setViewportView(jTextArea9);

        getContentPane().add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 170, 140));

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 36));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 670, 210, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
                // TODO add your handling code here:
}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mhrexpawrds().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables

}
