
import java.util.Random;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * passendetail.java
 *
 * Created on Jun 16, 2017, 11:33:36 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class passendetail extends javax.swing.JFrame {

    /** Creates new form passendetail */
    public passendetail() {
        initComponents();
        Uid_LB.setVisible(false);
       RAC_TF.setText("50");
       KKC_TF.setText("20");
       SBC_TF.setText("25");
       ST_TF.setText("40");
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Avail_TF = new javax.swing.JTextField();
        Trname_TF = new javax.swing.JTextField();
        Class_TF = new javax.swing.JTextField();
        Date_TF = new javax.swing.JTextField();
        Trno_TF = new javax.swing.JTextField();
        Quota_TF = new javax.swing.JTextField();
        Type_TF = new javax.swing.JTextField();
        Dist_TF = new javax.swing.JTextField();
        Resupto_TF = new javax.swing.JTextField();
        To_TF = new javax.swing.JTextField();
        From_TF = new javax.swing.JTextField();
        BP_TF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        nop_TF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sr_TF = new javax.swing.JTextField();
        sr_TF1 = new javax.swing.JTextField();
        sr_TF2 = new javax.swing.JTextField();
        name_TF1 = new javax.swing.JTextField();
        name_TF2 = new javax.swing.JTextField();
        age_TF1 = new javax.swing.JTextField();
        age_TF2 = new javax.swing.JTextField();
        name_TF = new javax.swing.JTextField();
        sex_TF = new javax.swing.JTextField();
        sex_TF1 = new javax.swing.JTextField();
        sex_TF2 = new javax.swing.JTextField();
        age_TF = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        S_TF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        S_TF1 = new javax.swing.JTextField();
        S_TF2 = new javax.swing.JTextField();
        S_TF3 = new javax.swing.JTextField();
        S_TF4 = new javax.swing.JTextField();
        S_TF5 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Id_TF = new javax.swing.JTextField();
        Id_TF1 = new javax.swing.JTextField();
        Id_TF2 = new javax.swing.JTextField();
        Id_TF3 = new javax.swing.JTextField();
        Id_TF4 = new javax.swing.JTextField();
        Id_TF5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Sr_TF5 = new javax.swing.JTextField();
        Sr_TF = new javax.swing.JTextField();
        Sr_TF1 = new javax.swing.JTextField();
        Sr_TF2 = new javax.swing.JTextField();
        Sr_TF3 = new javax.swing.JTextField();
        Sr_TF4 = new javax.swing.JTextField();
        Name_TF5 = new javax.swing.JTextField();
        Age_TF5 = new javax.swing.JTextField();
        Name_TF1 = new javax.swing.JTextField();
        Name_TF2 = new javax.swing.JTextField();
        Name_TF3 = new javax.swing.JTextField();
        Name_TF4 = new javax.swing.JTextField();
        Sex_TF5 = new javax.swing.JTextField();
        Ctz_TF5 = new javax.swing.JTextField();
        Age_TF1 = new javax.swing.JTextField();
        Age_TF2 = new javax.swing.JTextField();
        Age_TF3 = new javax.swing.JTextField();
        Age_TF4 = new javax.swing.JTextField();
        Name_TF = new javax.swing.JTextField();
        Sex_TF = new javax.swing.JTextField();
        Sex_TF1 = new javax.swing.JTextField();
        Sex_TF2 = new javax.swing.JTextField();
        Sex_TF3 = new javax.swing.JTextField();
        Sex_TF4 = new javax.swing.JTextField();
        Age_TF = new javax.swing.JTextField();
        Ctz_TF = new javax.swing.JTextField();
        Ctz_TF1 = new javax.swing.JTextField();
        Ctz_TF2 = new javax.swing.JTextField();
        Ctz_TF3 = new javax.swing.JTextField();
        Ctz_TF4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Tatkal_TF = new javax.swing.JTextField();
        TF_TF = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        RAC_TF = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        KKC_TF = new javax.swing.JTextField();
        Total_TF = new javax.swing.JTextField();
        TA_TF = new javax.swing.JTextField();
        ST_TF = new javax.swing.JTextField();
        SBC_TF = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tat_TF = new javax.swing.JTextField();
        Uid_LB = new javax.swing.JLabel();
        replan_btn = new javax.swing.JButton();
        makpay_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Ticket Reservation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Train Name:-");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel5.setText("Class:-");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel7.setText("Date:-");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel8.setText("Date:-");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel10.setText("From:-");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel12.setText("To:-");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel14.setText("Train No:-");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel16.setText("Boarding Point:-");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel18.setText("Reservation Upto:-");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jLabel21.setText("Quota:-");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel22.setText("Availbility:-");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel24.setText("Distance:-");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel26.setText("Type:-");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        Avail_TF.setEditable(false);
        jPanel2.add(Avail_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, -1));

        Trname_TF.setEditable(false);
        jPanel2.add(Trname_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        Class_TF.setEditable(false);
        jPanel2.add(Class_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 90, -1));

        Date_TF.setEditable(false);
        jPanel2.add(Date_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, -1));

        Trno_TF.setEditable(false);
        jPanel2.add(Trno_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 90, -1));

        Quota_TF.setEditable(false);
        jPanel2.add(Quota_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));

        Type_TF.setEditable(false);
        jPanel2.add(Type_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 90, -1));

        Dist_TF.setEditable(false);
        jPanel2.add(Dist_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, -1));

        Resupto_TF.setEditable(false);
        Resupto_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resupto_TFActionPerformed(evt);
            }
        });
        jPanel2.add(Resupto_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, -1));

        To_TF.setEditable(false);
        jPanel2.add(To_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, -1));

        From_TF.setEditable(false);
        jPanel2.add(From_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        BP_TF.setEditable(false);
        jPanel2.add(BP_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        jLabel28.setText("No Of Passengers:-");
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        nop_TF.setEditable(false);
        nop_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nop_TFActionPerformed(evt);
            }
        });
        jPanel2.add(nop_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 40, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 700, 260));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Child Passanger Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("S NO");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel4.setText("Name");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel6.setText("Age");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel9.setText("Sex");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        sr_TF.setEditable(false);
        jPanel4.add(sr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 20, -1));

        sr_TF1.setEditable(false);
        jPanel4.add(sr_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 20, -1));

        sr_TF2.setEditable(false);
        jPanel4.add(sr_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 20, -1));

        name_TF1.setEditable(false);
        jPanel4.add(name_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        name_TF2.setEditable(false);
        jPanel4.add(name_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));

        age_TF1.setEditable(false);
        jPanel4.add(age_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 40, -1));

        age_TF2.setEditable(false);
        jPanel4.add(age_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 40, -1));

        name_TF.setEditable(false);
        jPanel4.add(name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        sex_TF.setEditable(false);
        jPanel4.add(sex_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));

        sex_TF1.setEditable(false);
        jPanel4.add(sex_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, -1));

        sex_TF2.setEditable(false);
        jPanel4.add(sex_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, -1));

        age_TF.setEditable(false);
        jPanel4.add(age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 40, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 380, 150));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_TF.setEditable(false);
        jPanel5.add(S_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 20, -1));

        jLabel11.setText("S NO");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        S_TF1.setEditable(false);
        jPanel5.add(S_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 20, -1));

        S_TF2.setEditable(false);
        jPanel5.add(S_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 20, -1));

        S_TF3.setEditable(false);
        jPanel5.add(S_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 20, -1));

        S_TF4.setEditable(false);
        jPanel5.add(S_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 20, -1));

        S_TF5.setEditable(false);
        jPanel5.add(S_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 20, -1));

        jLabel13.setText("ID Card Type");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Id_TF.setEditable(false);
        jPanel5.add(Id_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        Id_TF1.setEditable(false);
        jPanel5.add(Id_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, -1));

        Id_TF2.setEditable(false);
        jPanel5.add(Id_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, -1));

        Id_TF3.setEditable(false);
        jPanel5.add(Id_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, -1));

        Id_TF4.setEditable(false);
        jPanel5.add(Id_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, -1));

        Id_TF5.setEditable(false);
        jPanel5.add(Id_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, -1));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 182, 210));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adult Passanger Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("S NO");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel17.setText("Senior Citizen");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel19.setText("Name");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel20.setText("Age");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel23.setText("Sex");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        Sr_TF5.setEditable(false);
        jPanel6.add(Sr_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 20, -1));

        Sr_TF.setEditable(false);
        jPanel6.add(Sr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 20, -1));

        Sr_TF1.setEditable(false);
        jPanel6.add(Sr_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 20, -1));

        Sr_TF2.setEditable(false);
        jPanel6.add(Sr_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 20, -1));

        Sr_TF3.setEditable(false);
        jPanel6.add(Sr_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 20, -1));

        Sr_TF4.setEditable(false);
        jPanel6.add(Sr_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 20, -1));

        Name_TF5.setEditable(false);
        jPanel6.add(Name_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, -1));

        Age_TF5.setEditable(false);
        jPanel6.add(Age_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 40, -1));

        Name_TF1.setEditable(false);
        jPanel6.add(Name_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, -1));

        Name_TF2.setEditable(false);
        jPanel6.add(Name_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, -1));

        Name_TF3.setEditable(false);
        jPanel6.add(Name_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        Name_TF4.setEditable(false);
        jPanel6.add(Name_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        Sex_TF5.setEditable(false);
        jPanel6.add(Sex_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, -1));

        Ctz_TF5.setEditable(false);
        jPanel6.add(Ctz_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 40, -1));

        Age_TF1.setEditable(false);
        jPanel6.add(Age_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 40, -1));

        Age_TF2.setEditable(false);
        jPanel6.add(Age_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 40, -1));

        Age_TF3.setEditable(false);
        jPanel6.add(Age_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, -1));

        Age_TF4.setEditable(false);
        jPanel6.add(Age_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 40, -1));

        Name_TF.setEditable(false);
        jPanel6.add(Name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, -1));

        Sex_TF.setEditable(false);
        jPanel6.add(Sex_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 90, -1));

        Sex_TF1.setEditable(false);
        jPanel6.add(Sex_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        Sex_TF2.setEditable(false);
        jPanel6.add(Sex_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, -1));

        Sex_TF3.setEditable(false);
        jPanel6.add(Sex_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));

        Sex_TF4.setEditable(false);
        jPanel6.add(Sex_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, -1));

        Age_TF.setEditable(false);
        jPanel6.add(Age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 40, -1));

        Ctz_TF.setEditable(false);
        jPanel6.add(Ctz_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, -1));

        Ctz_TF1.setEditable(false);
        jPanel6.add(Ctz_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 40, -1));

        Ctz_TF2.setEditable(false);
        jPanel6.add(Ctz_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 40, -1));

        Ctz_TF3.setEditable(false);
        jPanel6.add(Ctz_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 40, -1));

        Ctz_TF4.setEditable(false);
        jPanel6.add(Ctz_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, -1));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 444, 222));

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ticket Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Ticket Fare :-");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel25.setText("Tatkal Fare:-");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        Tatkal_TF.setEditable(false);
        jPanel8.add(Tatkal_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, -1));

        TF_TF.setEditable(false);
        jPanel8.add(TF_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 70, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, 100));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fare BreakUp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setText("Railway Agent Charges:-");
        jPanel9.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        RAC_TF.setEditable(false);
        jPanel9.add(RAC_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 60, -1));

        jLabel30.setText("Total Amount:-");
        jPanel9.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel31.setText("Service Tax:-");
        jPanel9.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel32.setText("Swacch Bharat Cess:-");
        jPanel9.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel34.setText("Krishi Kalyan Cess:-");
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel29.setText("Total");
        jPanel9.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        KKC_TF.setEditable(false);
        jPanel9.add(KKC_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 60, 20));

        Total_TF.setEditable(false);
        Total_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Total_TFActionPerformed(evt);
            }
        });
        jPanel9.add(Total_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 60, -1));

        TA_TF.setEditable(false);
        jPanel9.add(TA_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, 20));

        ST_TF.setEditable(false);
        jPanel9.add(ST_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 60, 20));

        SBC_TF.setEditable(false);
        jPanel9.add(SBC_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 60, 20));

        jLabel33.setText("Tatkal Charges:-");
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        tat_TF.setEditable(false);
        jPanel9.add(tat_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 60, -1));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 220, 190));
        jPanel7.add(Uid_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 60, 40));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 750, 240));

        replan_btn.setText("Replan");
        replan_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replan_btnActionPerformed(evt);
            }
        });
        jPanel3.add(replan_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 720, -1, -1));

        makpay_btn.setText("Make Payment");
        makpay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makpay_btnActionPerformed(evt);
            }
        });
        jPanel3.add(makpay_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 720, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 840, 770));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 1050, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Resupto_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resupto_TFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Resupto_TFActionPerformed

    private void replan_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replan_btnActionPerformed
 irctcbookingsearch i1=   new irctcbookingsearch();
 irctcbookingsearch.Uid_TF.setText(this.Uid_LB.getText());
 i1.setVisible(true);
  this.setVisible(false);// TODO add your handling code here:
}//GEN-LAST:event_replan_btnActionPerformed

    private void nop_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nop_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nop_TFActionPerformed

    private void Total_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Total_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Total_TFActionPerformed

    private void makpay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makpay_btnActionPerformed
{
       double distance =Double.parseDouble(Dist_TF.getText());
        double IA= (distance * 4);
        double IIA=  (distance * 2);
        double IIIA=  (distance + 335);
         double CC= (distance + 64);
         double SL=  (distance - 204);
         double IIS=  (distance - 365);

if(Class_TF.getText().equals("1A"))
{TA_TF.setText(Double.toString(IA));
TF_TF.setText(Double.toString(IA));}
else if(Class_TF.getText().equals("2A")) {
             TA_TF.setText(Double.toString(IIA));
TF_TF.setText(Double.toString(IIA));}
 else if (Class_TF.getText().equals("3A")) {
             TA_TF.setText(Double.toString(IIIA));
 TF_TF.setText(Double.toString(IIIA));}
 else if (Class_TF.getText().equals("CC")) {
             TA_TF.setText(Double.toString(CC));
 TF_TF.setText(Double.toString(CC));}
 else if(Class_TF.getText().equals("SL")) {
TA_TF.setText(Double.toString(SL));
 TF_TF.setText(Double.toString(SL));}
 else if (Class_TF.getText().equals("2S")) {
             TA_TF.setText(Double.toString(IIS));
 TF_TF.setText(Double.toString(IIS));}



if(Quota_TF.getText().equals("GENERAL")){Tatkal_TF.setText("0.0");tat_TF.setText("0.0");}
 if(Quota_TF.getText().equals("PREMIUM TATKAL")){Tatkal_TF.setText("350");tat_TF.setText("350");}
 if(Quota_TF.getText().equals("PHYSICALLY HANDICAP")){Tatkal_TF.setText("0.0");}
 if(Quota_TF.getText().equals("LADIES")){Tatkal_TF.setText("0.0");tat_TF.setText("0.0");}
 if(Quota_TF.getText().equals("TATKAL")){Tatkal_TF.setText("250");tat_TF.setText("250");}
double st,ta,sbc,kkc,rac,tat,Total;
st=Double.parseDouble(ST_TF.getText());
ta=Double.parseDouble(TA_TF.getText());
sbc=Double.parseDouble(SBC_TF.getText());
kkc=Double.parseDouble(KKC_TF.getText());
rac=Double.parseDouble(RAC_TF.getText());
tat=Double.parseDouble(tat_TF.getText());
Total=st+ta+sbc+kkc+rac+tat;
Total_TF.setText(""+Total);
        }
Payment a1 = new Payment();
Payment.SybTOT_TF.setText(this.Total_TF.getText());
Payment.uid_TF.setText(this.Uid_LB.getText());

Payment.Sr_TF.setText(this.Sr_TF.getText());
Payment.Sr_TF1.setText(this.Sr_TF1.getText());
Payment.Sr_TF2.setText(this.Sr_TF2.getText());
Payment.Sr_TF3.setText(this.Sr_TF3.getText());
Payment.Sr_TF4.setText(this.Sr_TF4.getText());
Payment.Sr_TF5.setText(this.Sr_TF5.getText());
Payment.Name_TF.setText(this.Name_TF.getText());
Payment.Name_TF1.setText(this.Name_TF1.getText());
Payment.Name_TF2.setText(this.Name_TF2.getText());
Payment.Name_TF3.setText(this.Name_TF3.getText());
Payment.Name_TF4.setText(this.Name_TF4.getText());
Payment.Name_TF5.setText(this.Name_TF5.getText());
Payment.Age_TF.setText(this.Age_TF.getText());
Payment.Age_TF1.setText(this.Age_TF1.getText());
Payment.Age_TF2.setText(this.Age_TF2.getText());
Payment.Age_TF3.setText(this.Age_TF3.getText());
Payment.Age_TF4.setText(this.Age_TF4.getText());
Payment.Age_TF5.setText(this.Age_TF5.getText());
Payment.Sex_TF.setText(this.Sex_TF.getText());
Payment.Sex_TF1.setText(this.Sex_TF1.getText());
Payment.Sex_TF2.setText(this.Sex_TF2.getText());
Payment.Sex_TF3.setText(this.Sex_TF3.getText());
Payment.Sex_TF4.setText(this.Sex_TF4.getText());
Payment.Sex_TF5.setText(this.Sex_TF5.getText());
Payment.Ctz_TF.setText(this.Ctz_TF.getText());
Payment.Ctz_TF1.setText(this.Ctz_TF1.getText());
Payment.Ctz_TF2.setText(this.Ctz_TF2.getText());
Payment.Ctz_TF3.setText(this.Ctz_TF3.getText());
Payment.Ctz_TF4.setText(this.Ctz_TF4.getText());
Payment.Ctz_TF5.setText(this.Ctz_TF5.getText());
Payment.S_TF.setText(this.S_TF.getText());
Payment.S_TF1.setText(this.S_TF1.getText());
Payment.S_TF2.setText(this.S_TF2.getText());
Payment.S_TF3.setText(this.S_TF3.getText());
Payment.S_TF4.setText(this.S_TF4.getText());
Payment.S_TF5.setText(this.S_TF5.getText());
Payment.Id_TF.setText(this.Id_TF.getText());
Payment.Id_TF1.setText(this.Id_TF1.getText());
Payment.Id_TF2.setText(this.Id_TF2.getText());
Payment.Id_TF3.setText(this.Id_TF3.getText());
Payment.Id_TF4.setText(this.Id_TF4.getText());
Payment.Id_TF5.setText(this.Id_TF5.getText());
Payment.sr_TF.setText(this.sr_TF.getText());
Payment.sr_TF1.setText(this.sr_TF1.getText());
Payment.sr_TF2.setText(this.sr_TF2.getText());
Payment.name_TF.setText(this.name_TF.getText());
Payment.name_TF1.setText(this.name_TF1.getText());
Payment.name_TF2.setText(this.name_TF2.getText());
Payment.age_TF.setText(this.age_TF.getText());
Payment.age_TF1.setText(this.age_TF1.getText());
Payment.age_TF2.setText(this.age_TF2.getText());
Payment.sex_TF.setText(this.sex_TF.getText());
Payment.sex_TF1.setText(this.sex_TF1.getText());
Payment.sex_TF2.setText(this.sex_TF2.getText());
Payment.Trname_TF.setText(this.Trname_TF.getText());
Payment.Class_TF.setText(this.Class_TF.getText());
Payment.Date_TF.setText(this.Date_TF.getText());
Payment.From_TF.setText(this.From_TF.getText());
Payment.To_TF.setText(this.To_TF.getText());
Payment.Trno_TF.setText(this.Trno_TF.getText());
Payment.BP_TF.setText(this.BP_TF.getText());
Payment.Resupto_TF.setText(this.Resupto_TF.getText());
Payment.Quota_TF.setText(this.Quota_TF.getText());
Payment.Avail_TF.setText(this.Avail_TF.getText());
Payment.nop_TF.setText(this.Dist_TF.getText());
Payment.Type_TF.setText(this.Type_TF.getText());
Payment.nop_TF.setText(this.nop_TF.getText());
Payment.Dist_TF1.setText(this.Dist_TF.getText());
Payment.GT_TF.setText(this.Total_TF.getText());
a1.setVisible(true);
this.setVisible(false);
        // TODO add your handling code here:
}//GEN-LAST:event_makpay_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new passendetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Age_TF;
    public static javax.swing.JTextField Age_TF1;
    public static javax.swing.JTextField Age_TF2;
    public static javax.swing.JTextField Age_TF3;
    public static javax.swing.JTextField Age_TF4;
    public static javax.swing.JTextField Age_TF5;
    public static javax.swing.JTextField Avail_TF;
    public static javax.swing.JTextField BP_TF;
    public static javax.swing.JTextField Class_TF;
    public static javax.swing.JTextField Ctz_TF;
    public static javax.swing.JTextField Ctz_TF1;
    public static javax.swing.JTextField Ctz_TF2;
    public static javax.swing.JTextField Ctz_TF3;
    public static javax.swing.JTextField Ctz_TF4;
    public static javax.swing.JTextField Ctz_TF5;
    public static javax.swing.JTextField Date_TF;
    public static javax.swing.JTextField Dist_TF;
    public static javax.swing.JTextField From_TF;
    public static javax.swing.JTextField Id_TF;
    public static javax.swing.JTextField Id_TF1;
    public static javax.swing.JTextField Id_TF2;
    public static javax.swing.JTextField Id_TF3;
    public static javax.swing.JTextField Id_TF4;
    public static javax.swing.JTextField Id_TF5;
    private javax.swing.JTextField KKC_TF;
    public static javax.swing.JTextField Name_TF;
    public static javax.swing.JTextField Name_TF1;
    public static javax.swing.JTextField Name_TF2;
    public static javax.swing.JTextField Name_TF3;
    public static javax.swing.JTextField Name_TF4;
    public static javax.swing.JTextField Name_TF5;
    public static javax.swing.JTextField Quota_TF;
    private javax.swing.JTextField RAC_TF;
    public static javax.swing.JTextField Resupto_TF;
    private javax.swing.JTextField SBC_TF;
    private javax.swing.JTextField ST_TF;
    public static javax.swing.JTextField S_TF;
    public static javax.swing.JTextField S_TF1;
    public static javax.swing.JTextField S_TF2;
    public static javax.swing.JTextField S_TF3;
    public static javax.swing.JTextField S_TF4;
    public static javax.swing.JTextField S_TF5;
    public static javax.swing.JTextField Sex_TF;
    public static javax.swing.JTextField Sex_TF1;
    public static javax.swing.JTextField Sex_TF2;
    public static javax.swing.JTextField Sex_TF3;
    public static javax.swing.JTextField Sex_TF4;
    public static javax.swing.JTextField Sex_TF5;
    public static javax.swing.JTextField Sr_TF;
    public static javax.swing.JTextField Sr_TF1;
    public static javax.swing.JTextField Sr_TF2;
    public static javax.swing.JTextField Sr_TF3;
    public static javax.swing.JTextField Sr_TF4;
    public static javax.swing.JTextField Sr_TF5;
    private javax.swing.JTextField TA_TF;
    private javax.swing.JTextField TF_TF;
    private javax.swing.JTextField Tatkal_TF;
    public static javax.swing.JTextField To_TF;
    private javax.swing.JTextField Total_TF;
    protected static javax.swing.JTextField Trname_TF;
    public static javax.swing.JTextField Trno_TF;
    public static javax.swing.JTextField Type_TF;
    public static javax.swing.JLabel Uid_LB;
    public static javax.swing.JTextField age_TF;
    public static javax.swing.JTextField age_TF1;
    public static javax.swing.JTextField age_TF2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makpay_btn;
    public static javax.swing.JTextField name_TF;
    public static javax.swing.JTextField name_TF1;
    public static javax.swing.JTextField name_TF2;
    public static javax.swing.JTextField nop_TF;
    private javax.swing.JButton replan_btn;
    public static javax.swing.JTextField sex_TF;
    public static javax.swing.JTextField sex_TF1;
    public static javax.swing.JTextField sex_TF2;
    public static javax.swing.JTextField sr_TF;
    public static javax.swing.JTextField sr_TF1;
    public static javax.swing.JTextField sr_TF2;
    private javax.swing.JTextField tat_TF;
    // End of variables declaration//GEN-END:variables

}
