import java.sql.* ;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;

/*
 * pass_update.java
 *
 * Created on May 17, 2017, 11:36:57 AM
 */

/**
 *
 * @author Kunal Shah
 */
public class pass_update extends javax.swing.JFrame {

    /** Creates new form pass_update */
    public pass_update() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        cp_txt = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        viewp_txt = new javax.swing.JCheckBox();
        p_txt = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true), "UPDATE PASSWORD", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("Current Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 81, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel2.setText("New Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 120, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 117, 125, -1));

        cp_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        cp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp_txtActionPerformed(evt);
            }
        });
        jPanel1.add(cp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 78, 125, -1));

        update_btn.setBackground(new java.awt.Color(0, 255, 0));
        update_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        update_btn.setText("UPDATE");
        update_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, -1, -1));

        viewp_txt.setFont(new java.awt.Font("Tahoma", 2, 16));
        viewp_txt.setText("Show Password");
        viewp_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewp_txtActionPerformed(evt);
            }
        });
        jPanel1.add(viewp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 116, 150, -1));

        p_txt.setFont(new java.awt.Font("Times New Roman", 0, 14));
        jPanel1.add(p_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 143, 125, 20));

        back_btn.setBackground(new java.awt.Color(255, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 450, 220));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cris.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 70));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 650, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2_edited.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 280, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sQ05dJt.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 650, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewp_txtActionPerformed
   if(viewp_txt.isSelected()){
     String pass =new String(jPasswordField1.getPassword());
     p_txt.setVisible(true);
     p_txt.setText(pass);
}
   else
   {
p_txt.setVisible(false);
} // TODO add your handling code here:
    }//GEN-LAST:event_viewp_txtActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
String cpass = cp_txt.getText();
String npass =jPasswordField1.getText();
        try{
        Class.forName("java.sql.DriverManager");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
        Statement stmt = con.createStatement();
        String q ="Update accounts set Password = '"+npass+"'  where Password = '"+ cpass +"';";
       stmt.executeUpdate(q);
JOptionPane.showMessageDialog(this,"Password Updated sucessfully");
    this.setVisible(false);
        }
        catch(Exception e){
         JOptionPane.showMessageDialog(this, e.getMessage());
        }

    
    // TODO add your handling code here:
    }//GEN-LAST:event_update_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.setVisible(false);        // TODO add your handling code here:
}//GEN-LAST:event_back_btnActionPerformed

    private void cp_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp_txtActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pass_update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JTextField cp_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel p_txt;
    private javax.swing.JButton update_btn;
    private javax.swing.JCheckBox viewp_txt;
    // End of variables declaration//GEN-END:variables

}
