

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileOutputStream;
import java.sql.* ;
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Payment.java
 *
 * Created on Jun 17, 2017, 8:59:53 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class Payment extends javax.swing.JFrame {

    /** Creates new form Payment */
    public Payment() {
        initComponents();
        Transactionid_TF.setVisible(false);
        Chart_TF.setText("Done");
        Chart_TF.setVisible(false);
        uid_TF.setVisible(false);

                String contain="0123456789";
Random rnd= new Random();
StringBuilder sb = new StringBuilder(10);
for (int i=0;i<10;i++)
{sb.append(contain.charAt(rnd.nextInt(contain.length())));}
String random =sb.toString();
Transactionid_TF.setText(random);

String containn="0123456789";
Random rndd= new Random();
StringBuilder sbb = new StringBuilder(10);
for (int i=0;i<10;i++)
{sbb.append(containn.charAt(rndd.nextInt(containn.length())));}
String randomm =sbb.toString();
Pnr_LB.setText(randomm);  }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        GT_TF = new javax.swing.JTextField();
        SybTOT_TF = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Pnr_LB = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cvv_txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nameoncard_txt = new javax.swing.JTextField();
        pay_btn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Avail_TF = new javax.swing.JTextField();
        Trname_TF = new javax.swing.JTextField();
        Class_TF = new javax.swing.JTextField();
        Date_TF = new javax.swing.JTextField();
        Trno_TF = new javax.swing.JTextField();
        Quota_TF = new javax.swing.JTextField();
        Type_TF = new javax.swing.JTextField();
        nop_TF = new javax.swing.JTextField();
        Resupto_TF = new javax.swing.JTextField();
        To_TF = new javax.swing.JTextField();
        From_TF = new javax.swing.JTextField();
        BP_TF = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        Dist_TF1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Adult_Passen = new javax.swing.JTextField();
        Child_Passen = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        S_TF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        S_TF1 = new javax.swing.JTextField();
        S_TF2 = new javax.swing.JTextField();
        S_TF3 = new javax.swing.JTextField();
        S_TF4 = new javax.swing.JTextField();
        S_TF5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Id_TF = new javax.swing.JTextField();
        Id_TF1 = new javax.swing.JTextField();
        Id_TF2 = new javax.swing.JTextField();
        Id_TF3 = new javax.swing.JTextField();
        Id_TF4 = new javax.swing.JTextField();
        Id_TF5 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        Sr_TF5 = new javax.swing.JTextField();
        Sr_TF = new javax.swing.JTextField();
        Sr_TF1 = new javax.swing.JTextField();
        Sr_TF2 = new javax.swing.JTextField();
        Sr_TF3 = new javax.swing.JTextField();
        Sr_TF4 = new javax.swing.JTextField();
        Name_TF5 = new javax.swing.JTextField();
        Age_TF5 = new javax.swing.JTextField();
        Name_TF1 = new javax.swing.JTextField();
        Name_TF2 = new javax.swing.JTextField();
        Name_TF3 = new javax.swing.JTextField();
        Name_TF4 = new javax.swing.JTextField();
        Sex_TF5 = new javax.swing.JTextField();
        Ctz_TF5 = new javax.swing.JTextField();
        Age_TF1 = new javax.swing.JTextField();
        Age_TF2 = new javax.swing.JTextField();
        Age_TF3 = new javax.swing.JTextField();
        Age_TF4 = new javax.swing.JTextField();
        Name_TF = new javax.swing.JTextField();
        Sex_TF = new javax.swing.JTextField();
        Sex_TF1 = new javax.swing.JTextField();
        Sex_TF2 = new javax.swing.JTextField();
        Sex_TF3 = new javax.swing.JTextField();
        Sex_TF4 = new javax.swing.JTextField();
        Age_TF = new javax.swing.JTextField();
        Ctz_TF = new javax.swing.JTextField();
        Ctz_TF1 = new javax.swing.JTextField();
        Ctz_TF2 = new javax.swing.JTextField();
        Ctz_TF3 = new javax.swing.JTextField();
        Ctz_TF4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        sr_TF = new javax.swing.JTextField();
        sr_TF1 = new javax.swing.JTextField();
        sr_TF2 = new javax.swing.JTextField();
        name_TF1 = new javax.swing.JTextField();
        name_TF2 = new javax.swing.JTextField();
        age_TF1 = new javax.swing.JTextField();
        age_TF2 = new javax.swing.JTextField();
        name_TF = new javax.swing.JTextField();
        sex_TF = new javax.swing.JTextField();
        sex_TF1 = new javax.swing.JTextField();
        sex_TF2 = new javax.swing.JTextField();
        age_TF = new javax.swing.JTextField();
        Transactionid_TF = new javax.swing.JTextField();
        Chart_TF = new javax.swing.JTextField();
        uid_TF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 70));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 640, 1340, 70));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Reservation Summary", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel1.setText("Grand Total:-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel2.setText("Sub Total:-");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel3.setText("Discount:- (-)");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 70, -1));

        GT_TF.setEditable(false);
        jPanel1.add(GT_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, -1));

        SybTOT_TF.setEditable(false);
        jPanel1.add(SybTOT_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, -1));

        jTextField3.setEditable(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, -1));
        jPanel1.add(Pnr_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 200, 50));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel35.setText("PNR NO");
        jPanel1.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        jPanel7.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 690, 180));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter Debit Card Details\n", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel4.setText("CVV(3-Digit Verification Number)");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, -1));
        jPanel2.add(cvv_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 70, 30));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14));
        jLabel7.setText("Name On Card (As it appears on card)");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 250, -1));
        jPanel2.add(nameoncard_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 290, 30));

        pay_btn.setText("Pay");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });
        jPanel2.add(pay_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 450, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cvv.jpg"))); // NOI18N
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 70, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/mini_kb_4_02.jpg"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 320, 30));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 630, 330));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5), "Ticket Reservation", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel9.setText("Train Name:-");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel10.setText("Class:-");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel11.setText("Date:-");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, -1, 20));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel13.setText("From:-");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel14.setText("To:-");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, 20));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel15.setText("Train No:-");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel16.setText("Boarding Point:-");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel18.setText("Reservation Upto:-");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel21.setText("Quota:-");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel22.setText("Availbility:-");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel24.setText("Distance:-");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel26.setText("Type:-");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));

        Avail_TF.setEditable(false);
        jPanel3.add(Avail_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 90, -1));

        Trname_TF.setEditable(false);
        jPanel3.add(Trname_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 90, -1));

        Class_TF.setEditable(false);
        jPanel3.add(Class_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 90, -1));

        Date_TF.setEditable(false);
        jPanel3.add(Date_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 90, -1));

        Trno_TF.setEditable(false);
        jPanel3.add(Trno_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 90, -1));

        Quota_TF.setEditable(false);
        jPanel3.add(Quota_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 90, -1));

        Type_TF.setEditable(false);
        jPanel3.add(Type_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 90, -1));

        nop_TF.setEditable(false);
        jPanel3.add(nop_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 30, -1));

        Resupto_TF.setEditable(false);
        Resupto_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Resupto_TFActionPerformed(evt);
            }
        });
        jPanel3.add(Resupto_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, -1));

        To_TF.setEditable(false);
        jPanel3.add(To_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 90, -1));

        From_TF.setEditable(false);
        jPanel3.add(From_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 90, -1));

        BP_TF.setEditable(false);
        jPanel3.add(BP_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 90, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel36.setText("No Of Passengers:-");
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        Dist_TF1.setEditable(false);
        jPanel3.add(Dist_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 90, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel5.setText("Adult:-");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel6.setText("Child:-");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        Adult_Passen.setEditable(false);
        jPanel3.add(Adult_Passen, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, -1));

        Child_Passen.setEditable(false);
        jPanel3.add(Child_Passen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 90, -1));

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 700, 260));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        S_TF.setEditable(false);
        jPanel5.add(S_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 20, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel17.setText("S NO");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 11, -1, -1));

        S_TF1.setEditable(false);
        jPanel5.add(S_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 20, -1));

        S_TF2.setEditable(false);
        jPanel5.add(S_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 20, -1));

        S_TF3.setEditable(false);
        jPanel5.add(S_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 20, -1));

        S_TF4.setEditable(false);
        jPanel5.add(S_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 20, -1));

        S_TF5.setEditable(false);
        jPanel5.add(S_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 20, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel19.setText("ID Card Type");
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        Id_TF.setEditable(false);
        jPanel5.add(Id_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 90, -1));

        Id_TF1.setEditable(false);
        jPanel5.add(Id_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 90, -1));

        Id_TF2.setEditable(false);
        jPanel5.add(Id_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 90, -1));

        Id_TF3.setEditable(false);
        jPanel5.add(Id_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 90, -1));

        Id_TF4.setEditable(false);
        jPanel5.add(Id_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 90, -1));

        Id_TF5.setEditable(false);
        jPanel5.add(Id_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 90, -1));

        jPanel7.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 182, 210));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Adult Passanger Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel20.setText("S NO");
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel23.setText("Senior Citizen");
        jPanel6.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(359, 20, 90, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel25.setText("Name");
        jPanel6.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel27.setText("Age");
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel28.setText("Sex");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        Sr_TF5.setEditable(false);
        jPanel6.add(Sr_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 20, -1));

        Sr_TF.setEditable(false);
        jPanel6.add(Sr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 20, -1));

        Sr_TF1.setEditable(false);
        jPanel6.add(Sr_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 20, -1));

        Sr_TF2.setEditable(false);
        jPanel6.add(Sr_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 20, -1));

        Sr_TF3.setEditable(false);
        jPanel6.add(Sr_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 20, -1));

        Sr_TF4.setEditable(false);
        jPanel6.add(Sr_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 20, -1));

        Name_TF5.setEditable(false);
        jPanel6.add(Name_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 90, -1));

        Age_TF5.setEditable(false);
        jPanel6.add(Age_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 40, -1));

        Name_TF1.setEditable(false);
        jPanel6.add(Name_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 90, -1));

        Name_TF2.setEditable(false);
        jPanel6.add(Name_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 90, -1));

        Name_TF3.setEditable(false);
        jPanel6.add(Name_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 90, -1));

        Name_TF4.setEditable(false);
        jPanel6.add(Name_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 90, -1));

        Sex_TF5.setEditable(false);
        jPanel6.add(Sex_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 90, -1));

        Ctz_TF5.setEditable(false);
        jPanel6.add(Ctz_TF5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 40, -1));

        Age_TF1.setEditable(false);
        jPanel6.add(Age_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 40, -1));

        Age_TF2.setEditable(false);
        jPanel6.add(Age_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 40, -1));

        Age_TF3.setEditable(false);
        jPanel6.add(Age_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 40, -1));

        Age_TF4.setEditable(false);
        jPanel6.add(Age_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 40, -1));

        Name_TF.setEditable(false);
        jPanel6.add(Name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, -1));

        Sex_TF.setEditable(false);
        jPanel6.add(Sex_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 90, -1));

        Sex_TF1.setEditable(false);
        jPanel6.add(Sex_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 90, -1));

        Sex_TF2.setEditable(false);
        jPanel6.add(Sex_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 90, -1));

        Sex_TF3.setEditable(false);
        jPanel6.add(Sex_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 90, -1));

        Sex_TF4.setEditable(false);
        jPanel6.add(Sex_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 90, -1));

        Age_TF.setEditable(false);
        jPanel6.add(Age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 40, -1));

        Ctz_TF.setEditable(false);
        jPanel6.add(Ctz_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 40, -1));

        Ctz_TF1.setEditable(false);
        jPanel6.add(Ctz_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 40, -1));

        Ctz_TF2.setEditable(false);
        jPanel6.add(Ctz_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 40, -1));

        Ctz_TF3.setEditable(false);
        jPanel6.add(Ctz_TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 40, -1));

        Ctz_TF4.setEditable(false);
        jPanel6.add(Ctz_TF4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 40, -1));

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 444, 222));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Child Passanger Details", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel29.setText("S NO");
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel30.setText("Name");
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel31.setText("Age");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12));
        jLabel32.setText("Sex");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        sr_TF.setEditable(false);
        jPanel4.add(sr_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 20, -1));

        sr_TF1.setEditable(false);
        jPanel4.add(sr_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 20, -1));

        sr_TF2.setEditable(false);
        jPanel4.add(sr_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 20, -1));

        name_TF1.setEditable(false);
        jPanel4.add(name_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 90, -1));

        name_TF2.setEditable(false);
        jPanel4.add(name_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, -1));

        age_TF1.setEditable(false);
        jPanel4.add(age_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 40, -1));

        age_TF2.setEditable(false);
        jPanel4.add(age_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 40, -1));

        name_TF.setEditable(false);
        jPanel4.add(name_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 90, -1));

        sex_TF.setEditable(false);
        jPanel4.add(sex_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 90, -1));

        sex_TF1.setEditable(false);
        jPanel4.add(sex_TF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 90, -1));

        sex_TF2.setEditable(false);
        jPanel4.add(sex_TF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 90, -1));

        age_TF.setEditable(false);
        jPanel4.add(age_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 40, -1));

        jPanel7.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 380, 150));

        Transactionid_TF.setEditable(false);
        Transactionid_TF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Transactionid_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Transactionid_TFActionPerformed(evt);
            }
        });
        jPanel7.add(Transactionid_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 340, 140, -1));

        Chart_TF.setEditable(false);
        Chart_TF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel7.add(Chart_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 360, 140, -1));

        uid_TF.setEditable(false);
        uid_TF.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        uid_TF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uid_TFActionPerformed(evt);
            }
        });
        jPanel7.add(uid_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 340, 90, -1));

        jScrollPane1.setViewportView(jPanel7);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1340, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed
String pnr =Pnr_LB.getText();
String trname =Trname_TF.getText();
String classs =Class_TF.getText();
String date =Date_TF.getText();
String from=From_TF.getText();
String to=To_TF.getText();
String trno=Trno_TF.getText();
String boarding=BP_TF.getText();
String resupto =Resupto_TF.getText();
String quota =Quota_TF.getText();
String avail =Avail_TF.getText();
String dist=nop_TF.getText();
String type=Type_TF.getText();
String total =GT_TF.getText();
String nop =nop_TF.getText();
String Chart =Chart_TF.getText();
String uid=uid_TF.getText();

String trid =Transactionid_TF.getText();
 int cvvno=Integer.parseInt(cvv_txt.getText());
 String Nameoncard=nameoncard_txt.getText();
 String n1=Name_TF.getText();
 String n2=Name_TF1.getText();
 String n3=Name_TF2.getText();
 String n4=Name_TF3.getText();
 String n5=Name_TF4.getText();
 String n6=Name_TF5.getText();
 String s1=Sex_TF.getText();
 String s2=Sex_TF1.getText();
 String s3=Sex_TF2.getText();
 String s4=Sex_TF3.getText();
 String s5=Sex_TF4.getText();
 String s6=Sex_TF5.getText();
 String N1=name_TF.getText();
 String N2=name_TF1.getText();
 String N3=name_TF2.getText();
 String S1=sex_TF.getText();
 String S2=sex_TF1.getText();
 String S3=sex_TF2.getText();

int cvv = 0 ;
String nameoncard = null;
try

{

    Class.forName("java.sql.DriverManager");

Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");

Statement stmt=con.createStatement();

String q = "SELECT * from bank where CVV ='"+cvvno+"';";
ResultSet rs = stmt.executeQuery(q);
if(rs.next())

{
cvv=rs.getInt(3);
nameoncard=rs.getString(4);
}

if(cvv == cvvno&&nameoncard.equals(Nameoncard)&&cvv_txt.getText().length()==3&&nameoncard_txt.getText().length()>0)
{
try
{
    Class.forName("java.sql.DriverManager");
 Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 String sql= "Insert into  bookings (PNR,Train_No,Train_Name,Date,From_Station, To_Station,Reservation_Upto,Boarding_Point,Class,No_Of_Passengers,Charting_Status, Quota, Type, Distance,Total_Amt,U_Id,Transaction_Id) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
PreparedStatement stm = conn.prepareStatement(sql);

 {
 stm.setString(1,pnr);
 stm.setString(2,trno);
 stm.setString(3,trname);
 stm.setString(4,date);
 stm.setString(5,from);
 stm.setString(6,to);
  stm.setString(7,resupto);
   stm.setString(8,boarding);
   stm.setString(9, classs);
 stm.setString(10,nop);
 stm.setString(11,Chart);
 stm.setString(12,quota);
 stm.setString(13,type);
 stm.setString(14,dist);
  stm.setString(15,total);
stm.setString(16,uid);
stm.setString(17,trid);
 stm.execute();
 stm.close();
 JOptionPane.showMessageDialog(null, "Transaction Sucessful ");
    }

 home h1 = new home();
    home.TF_UID.setText(this.uid_TF.getText());
     h1.setVisible(true);
      this.setVisible(false);
        }
catch (Exception e)
{JOptionPane.showMessageDialog(null, e.getMessage());}
}
    else if(cvv_txt.getText().length() < 3 && nameoncard_txt.getText().length() <= 0)
{
    JOptionPane.showMessageDialog(null, "Please Add A Bank Account");
this.setVisible(true);
}

Document doc=new Document();
      try{
      PdfWriter.getInstance(doc, new FileOutputStream(pnr+".pdf"));
      doc.open();
     doc.add(new Paragraph(new Chunk("RESERVATION SUMMARY")));
     doc.add(new Paragraph("Ticket Details"));
     doc.add(new Paragraph("****************************************************************************************************************"));
     PdfPTable pt= new PdfPTable(4);
     PdfPCell cell=new PdfPCell(new Paragraph("Booking"));
     cell.setColspan(6);
     cell.setHorizontalAlignment(Element.ALIGN_CENTER);
     cell.setBackgroundColor(BaseColor.BLUE);
     cell.setPadding(10.0f);
     pt.addCell(cell);
      pt.addCell("PNR Number");
      pt.addCell(pnr);
      pt.addCell("Train No");
      cell.setBackgroundColor(BaseColor.GREEN);
      pt.addCell(trno);
      pt.addCell("Train Name");
      pt.addCell(trname);
      pt.addCell("Date");
      pt.addCell(date);
      pt.addCell("From");
      pt.addCell(from);
      pt.addCell("To");
      pt.addCell(to);
      pt.addCell("Reservation Upto");
      pt.addCell(resupto);
      pt.addCell("Boarding Point");
      pt.addCell(boarding);
      pt.addCell("Class");
      pt.addCell(classs);
      pt.addCell("Number Of Passengers");
      pt.addCell(nop);
      pt.addCell("Quota");
      pt.addCell(quota);
      pt.addCell("Type");
      pt.addCell(type);
      pt.addCell("Total");
      pt.addCell(total);
      pt.addCell("User Id");
      pt.addCell(uid);
      pt.addCell("Transaction Id");
      pt.addCell(trid);
      doc.add(pt);
      doc.add(new Paragraph("****************************************************************************************************************"));
      PdfPTable ptt= new PdfPTable(4);
     PdfPCell celll=new PdfPCell(new Paragraph("ADULT PESSENGER DETAILS"));
     celll.setColspan(6);
     celll.setHorizontalAlignment(Element.ALIGN_CENTER);
     celll.setBackgroundColor(BaseColor.YELLOW);
     celll.setPadding(10.0f);
     ptt.addCell(celll);
      ptt.addCell("Passenger 1");
      ptt.addCell(n1+"("+s1+")");
      ptt.addCell("Passenger 2");
      celll.setBackgroundColor(BaseColor.GREEN);
      ptt.addCell(n2+"("+s2+")");
      ptt.addCell("Passenger 3");
      ptt.addCell(n3+"("+s3+")");
      ptt.addCell("Passenger 4");
      ptt.addCell(n4+"("+s4+")");
      ptt.addCell("Passenger 5");
      ptt.addCell(n5+"("+s5+")");
      ptt.addCell("Passenger 6");
      ptt.addCell(n6+"("+s6+")");
      doc.add(ptt);
      doc.add(new Paragraph("****************************************************************************************************************"));
      PdfPTable pttt= new PdfPTable(4);
     PdfPCell cellll=new PdfPCell(new Paragraph("CHILD PESSENGER DETAILS"));
     cellll.setColspan(6);
     cellll.setHorizontalAlignment(Element.ALIGN_CENTER);
     cellll.setBackgroundColor(BaseColor.YELLOW);
     cellll.setPadding(10.0f);
     pttt.addCell(cellll);
      pttt.addCell("Passenger 1");
      pttt.addCell(N1+"("+S1+")");
      pttt.addCell("Passenger 2");
      celll.setBackgroundColor(BaseColor.GREEN);
      pttt.addCell(N2+"("+S2+")");
      pttt.addCell("Passenger 3");
      pttt.addCell(N3+"("+S3+")");
      pttt.addCell("");
      pttt.addCell("");
      doc.add(pttt);
      doc.add(new Paragraph("****************************************************************************************************************"));
      doc.close();
     }
      catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}
}
catch (Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}// TODO add your handling code here:
    }//GEN-LAST:event_pay_btnActionPerformed

    private void Resupto_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Resupto_TFActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_Resupto_TFActionPerformed

    private void Transactionid_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Transactionid_TFActionPerformed
Transactionid_TF.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_Transactionid_TFActionPerformed

    private void uid_TFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uid_TFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uid_TFActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adult_Passen;
    public static javax.swing.JTextField Age_TF;
    public static javax.swing.JTextField Age_TF1;
    public static javax.swing.JTextField Age_TF2;
    public static javax.swing.JTextField Age_TF3;
    public static javax.swing.JTextField Age_TF4;
    public static javax.swing.JTextField Age_TF5;
    public static javax.swing.JTextField Avail_TF;
    public static javax.swing.JTextField BP_TF;
    private javax.swing.JTextField Chart_TF;
    private javax.swing.JTextField Child_Passen;
    public static javax.swing.JTextField Class_TF;
    public static javax.swing.JTextField Ctz_TF;
    public static javax.swing.JTextField Ctz_TF1;
    public static javax.swing.JTextField Ctz_TF2;
    public static javax.swing.JTextField Ctz_TF3;
    public static javax.swing.JTextField Ctz_TF4;
    public static javax.swing.JTextField Ctz_TF5;
    public static javax.swing.JTextField Date_TF;
    public static javax.swing.JTextField Dist_TF1;
    public static javax.swing.JTextField From_TF;
    public static javax.swing.JTextField GT_TF;
    public static javax.swing.JTextField Id_TF;
    public static javax.swing.JTextField Id_TF1;
    public static javax.swing.JTextField Id_TF2;
    public static javax.swing.JTextField Id_TF3;
    public static javax.swing.JTextField Id_TF4;
    public static javax.swing.JTextField Id_TF5;
    public static javax.swing.JTextField Name_TF;
    public static javax.swing.JTextField Name_TF1;
    public static javax.swing.JTextField Name_TF2;
    public static javax.swing.JTextField Name_TF3;
    public static javax.swing.JTextField Name_TF4;
    public static javax.swing.JTextField Name_TF5;
    public static javax.swing.JLabel Pnr_LB;
    public static javax.swing.JTextField Quota_TF;
    public static javax.swing.JTextField Resupto_TF;
    public static javax.swing.JTextField S_TF;
    public static javax.swing.JTextField S_TF1;
    public static javax.swing.JTextField S_TF2;
    public static javax.swing.JTextField S_TF3;
    public static javax.swing.JTextField S_TF4;
    public static javax.swing.JTextField S_TF5;
    public static javax.swing.JTextField Sex_TF;
    public static javax.swing.JTextField Sex_TF1;
    public static javax.swing.JTextField Sex_TF2;
    public static javax.swing.JTextField Sex_TF3;
    public static javax.swing.JTextField Sex_TF4;
    public static javax.swing.JTextField Sex_TF5;
    public static javax.swing.JTextField Sr_TF;
    public static javax.swing.JTextField Sr_TF1;
    public static javax.swing.JTextField Sr_TF2;
    public static javax.swing.JTextField Sr_TF3;
    public static javax.swing.JTextField Sr_TF4;
    public static javax.swing.JTextField Sr_TF5;
    public static javax.swing.JTextField SybTOT_TF;
    public static javax.swing.JTextField To_TF;
    public static javax.swing.JTextField Transactionid_TF;
    public static javax.swing.JTextField Trname_TF;
    public static javax.swing.JTextField Trno_TF;
    public static javax.swing.JTextField Type_TF;
    public static javax.swing.JTextField age_TF;
    public static javax.swing.JTextField age_TF1;
    public static javax.swing.JTextField age_TF2;
    private javax.swing.JTextField cvv_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField3;
    public static javax.swing.JTextField name_TF;
    public static javax.swing.JTextField name_TF1;
    public static javax.swing.JTextField name_TF2;
    private javax.swing.JTextField nameoncard_txt;
    public static javax.swing.JTextField nop_TF;
    private javax.swing.JButton pay_btn;
    public static javax.swing.JTextField sex_TF;
    public static javax.swing.JTextField sex_TF1;
    public static javax.swing.JTextField sex_TF2;
    public static javax.swing.JTextField sr_TF;
    public static javax.swing.JTextField sr_TF1;
    public static javax.swing.JTextField sr_TF2;
    public static javax.swing.JTextField uid_TF;
    // End of variables declaration//GEN-END:variables

}
