import java.sql.* ;
import java.awt.Color;
import javax.swing.JOptionPane;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pnrstatus.java
 *
 * Created on Jun 14, 2017, 11:01:11 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class pnrstatus extends javax.swing.JFrame {

    /** Creates new form pnrstatus */
    public pnrstatus() {
        initComponents();uid_LB.setVisible(false);
      bp_txt.setEnabled(false);nop_lb.setEnabled(false);resupto_lb.setEnabled(false);tostn_lb.setEnabled(false);bp_lb.setEnabled(false);class_txt.setEnabled(false);date_lb.setEnabled(false);pnr1_lb.setEnabled(false);charting_lb.setEnabled(false);trname_txt.setEnabled(false);charting_txt.setEnabled(false); class_lb.setEnabled(false); frmstn_txt.setEnabled(false); date_txt.setEnabled(false);pnr1_txt.setEnabled(false);tostn_txt.setEnabled(false); frmstn_lb.setEnabled(false);trno_lb.setEnabled(false); trname_lb.setEnabled(false);nop_txt.setEnabled(false);resupto_txt.setEnabled(false); trno_txt.setEnabled(false);
      bp_txt.setVisible(false);nop_lb.setVisible(false);resupto_lb.setVisible(false);tostn_lb.setVisible(false);bp_lb.setVisible(false);class_txt.setVisible(false);date_lb.setVisible(false);pnr1_lb.setVisible(false);charting_lb.setVisible(false);trname_txt.setVisible(false);charting_txt.setVisible(false); class_lb.setVisible(false); frmstn_txt.setVisible(false); date_txt.setVisible(false);pnr1_txt.setVisible(false);tostn_txt.setVisible(false); frmstn_lb.setVisible(false);trno_lb.setVisible(false); trname_lb.setVisible(false);nop_txt.setVisible(false);resupto_txt.setVisible(false); trno_txt.setVisible(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnrpanel = new javax.swing.JPanel();
        pnr1_lb = new javax.swing.JLabel();
        date_lb = new javax.swing.JLabel();
        resupto_lb = new javax.swing.JLabel();
        nop_lb = new javax.swing.JLabel();
        trno_lb = new javax.swing.JLabel();
        frmstn_lb = new javax.swing.JLabel();
        bp_lb = new javax.swing.JLabel();
        charting_lb = new javax.swing.JLabel();
        trname_lb = new javax.swing.JLabel();
        tostn_lb = new javax.swing.JLabel();
        class_lb = new javax.swing.JLabel();
        pnr1_txt = new javax.swing.JTextField();
        date_txt = new javax.swing.JTextField();
        resupto_txt = new javax.swing.JTextField();
        nop_txt = new javax.swing.JTextField();
        trno_txt = new javax.swing.JTextField();
        frmstn_txt = new javax.swing.JTextField();
        bp_txt = new javax.swing.JTextField();
        charting_txt = new javax.swing.JTextField();
        trname_txt = new javax.swing.JTextField();
        tostn_txt = new javax.swing.JTextField();
        class_txt = new javax.swing.JTextField();
        pnr_lb = new javax.swing.JLabel();
        pnr_txt = new javax.swing.JTextField();
        getstatus_btn = new javax.swing.JButton();
        checknew_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        uid_LB = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnrpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnr1_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        pnr1_lb.setForeground(new java.awt.Color(255, 255, 255));
        pnr1_lb.setText("PNR Number :");
        pnrpanel.add(pnr1_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        date_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        date_lb.setForeground(new java.awt.Color(255, 255, 255));
        date_lb.setText("Date:");
        pnrpanel.add(date_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        resupto_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        resupto_lb.setForeground(new java.awt.Color(255, 255, 255));
        resupto_lb.setText("Reservation upto:");
        pnrpanel.add(resupto_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        nop_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        nop_lb.setForeground(new java.awt.Color(255, 255, 255));
        nop_lb.setText("No of passengers:");
        pnrpanel.add(nop_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        trno_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        trno_lb.setForeground(new java.awt.Color(255, 255, 255));
        trno_lb.setText("Train Number:");
        pnrpanel.add(trno_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 130, -1));

        frmstn_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        frmstn_lb.setForeground(new java.awt.Color(255, 255, 255));
        frmstn_lb.setText("From station:");
        pnrpanel.add(frmstn_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        bp_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        bp_lb.setForeground(new java.awt.Color(255, 255, 255));
        bp_lb.setText("Boarding point:");
        pnrpanel.add(bp_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

        charting_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        charting_lb.setForeground(new java.awt.Color(255, 255, 255));
        charting_lb.setText("Charting status:");
        pnrpanel.add(charting_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, -1, -1));

        trname_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        trname_lb.setForeground(new java.awt.Color(255, 255, 255));
        trname_lb.setText("Train Name:");
        pnrpanel.add(trname_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, -1));

        tostn_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        tostn_lb.setForeground(new java.awt.Color(255, 255, 255));
        tostn_lb.setText("To station:");
        pnrpanel.add(tostn_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        class_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        class_lb.setForeground(new java.awt.Color(255, 255, 255));
        class_lb.setText("Class:");
        pnrpanel.add(class_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, -1, -1));

        pnr1_txt.setEditable(false);
        pnrpanel.add(pnr1_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 110, -1));

        date_txt.setEditable(false);
        pnrpanel.add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 110, 20));

        resupto_txt.setEditable(false);
        pnrpanel.add(resupto_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 110, -1));

        nop_txt.setEditable(false);
        pnrpanel.add(nop_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 110, -1));

        trno_txt.setEditable(false);
        trno_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trno_txtActionPerformed(evt);
            }
        });
        pnrpanel.add(trno_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 110, -1));

        frmstn_txt.setEditable(false);
        pnrpanel.add(frmstn_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 110, -1));

        bp_txt.setEditable(false);
        pnrpanel.add(bp_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 110, -1));

        charting_txt.setEditable(false);
        pnrpanel.add(charting_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 250, 110, -1));

        trname_txt.setEditable(false);
        pnrpanel.add(trname_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 100, -1));

        tostn_txt.setEditable(false);
        pnrpanel.add(tostn_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 100, -1));

        class_txt.setEditable(false);
        pnrpanel.add(class_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 100, -1));

        pnr_lb.setFont(new java.awt.Font("Times New Roman", 1, 18));
        pnr_lb.setForeground(new java.awt.Color(255, 255, 255));
        pnr_lb.setText("PNR Number");
        pnrpanel.add(pnr_lb, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));
        pnrpanel.add(pnr_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 109, -1));

        getstatus_btn.setBackground(new java.awt.Color(0, 255, 0));
        getstatus_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        getstatus_btn.setForeground(new java.awt.Color(255, 255, 255));
        getstatus_btn.setText("Get Status");
        getstatus_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getstatus_btnActionPerformed(evt);
            }
        });
        pnrpanel.add(getstatus_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, 30));

        checknew_btn.setBackground(new java.awt.Color(0, 255, 0));
        checknew_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        checknew_btn.setForeground(new java.awt.Color(255, 255, 255));
        checknew_btn.setText("Check New Status");
        checknew_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checknew_btnActionPerformed(evt);
            }
        });
        pnrpanel.add(checknew_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, 30));

        back_btn.setBackground(new java.awt.Color(255, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Back");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        pnrpanel.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, -1, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sQ05dJt.jpg"))); // NOI18N
        pnrpanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 410));

        uid_LB.setText("jLabel16");
        pnrpanel.add(uid_LB, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, -1, -1));

        getContentPane().add(pnrpanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 730, 410));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 1350, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trno_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trno_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trno_txtActionPerformed

    private void getstatus_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getstatus_btnActionPerformed

   String pnr =pnr_txt.getText();
   try
{
    Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
 Statement stmt;
 stmt = con.createStatement();
 String q="Select * from  bookings where PNR='"+pnr+"'";
 ResultSet rs = stmt.executeQuery(q);
 if(pnr_txt.getText().equals("")){JOptionPane.showMessageDialog(null, "Please enter PNR Number");}
  String PNR="";
  String trno="";
  String trname="";
  String date="";
  String from="";
  String to="";
  String upto="";
  String bp="";
  String Class="";
  String nop="";
  String chart="";

 while(rs.next()){
    PNR=rs.getString(1);
    trno= rs.getString(2);
    trname=rs.getString(3);
    date= rs.getString(4);
    from=rs.getString(5);
    to= rs.getString(6);
    upto=rs.getString(7);
    bp= rs.getString(8);
    Class=rs.getString(9);
    nop= rs.getString(10);
    chart=rs.getString(11);

    if( pnr_txt.getText().equals(PNR))
    {
      pnr1_txt.setText(PNR);
      date_txt.setText(date);
      resupto_txt.setText(upto);
       nop_txt.setText(nop);
        trno_txt.setText(trno);
         frmstn_txt.setText(from);
          bp_txt.setText(bp);
           charting_txt.setText(chart);
            trname_txt.setText(trname);
             tostn_txt.setText(to);
              class_txt.setText(Class);
              bp_txt.setEnabled(true);nop_lb.setEnabled(true);resupto_lb.setEnabled(true);tostn_lb.setEnabled(true);bp_lb.setEnabled(true);class_txt.setEnabled(true);date_lb.setEnabled(true);pnr1_lb.setEnabled(true);charting_lb.setEnabled(true);trname_txt.setEnabled(true);charting_txt.setEnabled(true); class_lb.setEnabled(true); frmstn_txt.setEnabled(true); date_txt.setEnabled(true);pnr1_txt.setEnabled(true);tostn_txt.setEnabled(true); frmstn_lb.setEnabled(true);trno_lb.setEnabled(true); trname_lb.setEnabled(true);nop_txt.setEnabled(true);resupto_txt.setEnabled(true); trno_txt.setEnabled(true);
      bp_txt.setVisible(true);nop_lb.setVisible(true);resupto_lb.setVisible(true);tostn_lb.setVisible(true);bp_lb.setVisible(true);class_txt.setVisible(true);date_lb.setVisible(true);pnr1_lb.setVisible(true);charting_lb.setVisible(true);trname_txt.setVisible(true);charting_txt.setVisible(true); class_lb.setVisible(true); frmstn_txt.setVisible(true); date_txt.setVisible(true);pnr1_txt.setVisible(true);tostn_txt.setVisible(true); frmstn_lb.setVisible(true);trno_lb.setVisible(true); trname_lb.setVisible(true);nop_txt.setVisible(true);resupto_txt.setVisible(true); trno_txt.setVisible(true);
    }
 else if(pnr_txt.getText()!=(PNR))
 {
 pnrpanel.setEnabled(true);
        pnrpanel.setVisible(true);
        bp_txt.setEnabled(false);nop_lb.setEnabled(false);resupto_lb.setEnabled(false);tostn_lb.setEnabled(false);bp_lb.setEnabled(false);class_txt.setEnabled(false);date_lb.setEnabled(false);pnr1_lb.setEnabled(false);charting_lb.setEnabled(false);trname_txt.setEnabled(false);charting_txt.setEnabled(false); class_lb.setEnabled(false); frmstn_txt.setEnabled(false); date_txt.setEnabled(false);pnr1_txt.setEnabled(false);tostn_txt.setEnabled(false); frmstn_lb.setEnabled(false);trno_lb.setEnabled(false); trname_lb.setEnabled(false);nop_txt.setEnabled(false);resupto_txt.setEnabled(false); trno_txt.setEnabled(false);
      bp_txt.setVisible(false);nop_lb.setVisible(false);resupto_lb.setVisible(false);tostn_lb.setVisible(false);bp_lb.setVisible(false);class_txt.setVisible(false);date_lb.setVisible(false);pnr1_lb.setVisible(false);charting_lb.setVisible(false);trname_txt.setVisible(false);charting_txt.setVisible(false); class_lb.setVisible(false); frmstn_txt.setVisible(false); date_txt.setVisible(false);pnr1_txt.setVisible(false);tostn_txt.setVisible(false); frmstn_lb.setVisible(false);trno_lb.setVisible(false); trname_lb.setVisible(false);nop_txt.setVisible(false);resupto_txt.setVisible(false); trno_txt.setVisible(false);
        JOptionPane.showMessageDialog(null,"Check Your PNR Number");}
 }
   }
   catch(Exception e)
   {JOptionPane.showMessageDialog(null,e.getMessage());}


 // TODO add your handling code here:
    }//GEN-LAST:event_getstatus_btnActionPerformed

    private void checknew_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checknew_btnActionPerformed
pnr_txt.setText("");
pnr1_txt.setText("");
date_txt.setText("");
resupto_txt.setText("");
nop_txt.setText("");
trno_txt.setText("");
frmstn_txt.setText("");
bp_txt.setText("");
charting_txt.setText("");
trname_txt.setText("");
tostn_txt.setText("");
class_txt.setText("");
bp_txt.setEnabled(false);nop_lb.setEnabled(false);resupto_lb.setEnabled(false);tostn_lb.setEnabled(false);bp_lb.setEnabled(false);class_txt.setEnabled(false);date_lb.setEnabled(false);pnr1_lb.setEnabled(false);charting_lb.setEnabled(false);trname_txt.setEnabled(false);charting_txt.setEnabled(false); class_lb.setEnabled(false); frmstn_txt.setEnabled(false); date_txt.setEnabled(false);pnr1_txt.setEnabled(false);tostn_txt.setEnabled(false); frmstn_lb.setEnabled(false);trno_lb.setEnabled(false); trname_lb.setEnabled(false);nop_txt.setEnabled(false);resupto_txt.setEnabled(false); trno_txt.setEnabled(false);
bp_txt.setVisible(false);nop_lb.setVisible(false);resupto_lb.setVisible(false);tostn_lb.setVisible(false);bp_lb.setVisible(false);class_txt.setVisible(false);date_lb.setVisible(false);pnr1_lb.setVisible(false);charting_lb.setVisible(false);trname_txt.setVisible(false);charting_txt.setVisible(false); class_lb.setVisible(false); frmstn_txt.setVisible(false); date_txt.setVisible(false);pnr1_txt.setVisible(false);tostn_txt.setVisible(false); frmstn_lb.setVisible(false);trno_lb.setVisible(false); trname_lb.setVisible(false);nop_txt.setVisible(false);resupto_txt.setVisible(false); trno_txt.setVisible(false);


 // TODO add your handling code here:
    }//GEN-LAST:event_checknew_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
home h1 =new home();
home.TF_UID.setText(this.uid_LB.getText());
h1.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pnrstatus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel bp_lb;
    private javax.swing.JTextField bp_txt;
    private javax.swing.JLabel charting_lb;
    private javax.swing.JTextField charting_txt;
    private javax.swing.JButton checknew_btn;
    private javax.swing.JLabel class_lb;
    private javax.swing.JTextField class_txt;
    private javax.swing.JLabel date_lb;
    private javax.swing.JTextField date_txt;
    private javax.swing.JLabel frmstn_lb;
    private javax.swing.JTextField frmstn_txt;
    private javax.swing.JButton getstatus_btn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel nop_lb;
    private javax.swing.JTextField nop_txt;
    private javax.swing.JLabel pnr1_lb;
    private javax.swing.JTextField pnr1_txt;
    private javax.swing.JLabel pnr_lb;
    private javax.swing.JTextField pnr_txt;
    private javax.swing.JPanel pnrpanel;
    private javax.swing.JLabel resupto_lb;
    private javax.swing.JTextField resupto_txt;
    private javax.swing.JLabel tostn_lb;
    private javax.swing.JTextField tostn_txt;
    private javax.swing.JLabel trname_lb;
    private javax.swing.JTextField trname_txt;
    private javax.swing.JLabel trno_lb;
    private javax.swing.JTextField trno_txt;
    public static javax.swing.JLabel uid_LB;
    // End of variables declaration//GEN-END:variables

}
