import java.awt.Color;
import java.io.File;
import java.sql.*;/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * viewbookings.java
 *
 * Created on Jun 20, 2017, 6:08:43 PM
 */

/**
 *
 * @author Kunal Shah
 */
public class viewbookings extends javax.swing.JFrame {

    /** Creates new form viewbookings */
    public viewbookings() {
        initComponents();
        booking_table.setVisible(false);
        booking_table.setEnabled(false);
        getContentPane().setBackground(new Color(51,0,204));
        Uid_lB.setVisible(false);
        trid_txt.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        uid_TF = new javax.swing.JTextField();
        go_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        booking_table = new javax.swing.JTable();
        cancel_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        Uid_lB = new javax.swing.JLabel();
        viewdetail_btn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        trid_txt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Booking Ticket History", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 3, 24))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18));
        jLabel1.setText("User Id");
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        uid_TF.setFont(new java.awt.Font("Times New Roman", 0, 18));
        jPanel2.add(uid_TF, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 30));

        go_btn.setBackground(new java.awt.Color(0, 255, 0));
        go_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        go_btn.setForeground(new java.awt.Color(255, 255, 255));
        go_btn.setText("Go");
        go_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        go_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                go_btnActionPerformed(evt);
            }
        });
        jPanel2.add(go_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 200, 90));

        booking_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PNR", "Train No", "Train Name", "From", "To", "Date", "Number Of Passengers"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        booking_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(booking_table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 630, 110));

        cancel_btn.setBackground(new java.awt.Color(255, 0, 0));
        cancel_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        cancel_btn.setForeground(new java.awt.Color(255, 255, 255));
        cancel_btn.setText("Cancel Ticket");
        cancel_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });
        jPanel1.add(cancel_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        back_btn.setBackground(new java.awt.Color(255, 0, 0));
        back_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        back_btn.setForeground(new java.awt.Color(255, 255, 255));
        back_btn.setText("Back");
        back_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 100, 30));
        jPanel1.add(Uid_lB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 70, 30));

        viewdetail_btn.setBackground(new java.awt.Color(0, 255, 0));
        viewdetail_btn.setFont(new java.awt.Font("Times New Roman", 1, 18));
        viewdetail_btn.setForeground(new java.awt.Color(255, 255, 255));
        viewdetail_btn.setText("View Details(in PDF)");
        viewdetail_btn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        viewdetail_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdetail_btnActionPerformed(evt);
            }
        });
        jPanel1.add(viewdetail_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("To View Complete Details Please Click on the Booking you want to see details of.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sQ05dJt.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 730, 360));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 740, 400));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/irctc.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1340, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/partner.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1340, 60));

        trid_txt.setEditable(false);
        getContentPane().add(trid_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 210, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void go_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_go_btnActionPerformed
String uid =uid_TF.getText();
String Uid = null;
String trno = null;
String trname = null;
String from = null;
String date = null;
String nop = null;
String to = null;
String pnr = null;
DefaultTableModel dm =(DefaultTableModel)booking_table.getModel();
          int len =dm.getRowCount();
          for(int i =1;i<=len;i++){
              dm.removeRow(0);}
  try{

 Class.forName("java.sql.DriverManager");
 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","admin");
Statement stmt=con.createStatement();

String q = "SELECT * from bookings where U_Id='"+uid+"';";
  ResultSet rs = stmt.executeQuery(q);
  while(rs.next())
{Uid = rs.getString(16);
trno= rs.getString(2);
trname= rs.getString(3);
from= rs.getString(5);
to= rs.getString(6);
date= rs.getString(4);
nop= rs.getString(10);
pnr=rs.getString(1);
  if(uid.equals(Uid)){
dm.addRow(new Object[]{pnr,trno,trname,from,to,date,nop});
booking_table.setVisible(true);
booking_table.setEnabled(true);
}
    else if(!uid.equals(Uid) || uid.length() <= 0)
    {
        JOptionPane.showMessageDialog(null, "Please Check Your User Id");
    }
  }


  }
catch(Exception e){JOptionPane.showMessageDialog(null, e.getMessage());}
        // TODO add your handling code here:
    }//GEN-LAST:event_go_btnActionPerformed

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
Cancel_Irctc i1 =new Cancel_Irctc();
Cancel_Irctc.uid_lb.setText(this.Uid_lB.getText());
i1.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
home h1 = new home();
home.TF_UID.setText(this.Uid_lB.getText());
h1.setVisible(true);
this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_back_btnActionPerformed

    private void booking_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_tableMouseClicked
    int row=booking_table.getSelectedRow();
    String b =(String) booking_table.getValueAt(row, 0);
    trid_txt.setText(b);
    // TODO add your handling code here:
    }//GEN-LAST:event_booking_tableMouseClicked

    private void viewdetail_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdetail_btnActionPerformed
String trid=trid_txt.getText();
if(trid.equals(""))
{JOptionPane.showMessageDialog(null, "Please Click On Table To View Ticket[in .pdf form]");}
 else
{
    try {
Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler "+"C:\\Users\\Admin\\Desktop\\IP Projects\\railway reservation\\Railway Reservation\\"+trid+".pdf");
    }
    catch(Exception e){JOptionPane.showMessageDialog(null, "No Ticket Found ...");} 
        }// TODO add your handling code here:
    }//GEN-LAST:event_viewdetail_btnActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewbookings().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Uid_lB;
    private javax.swing.JButton back_btn;
    private javax.swing.JTable booking_table;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JButton go_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField trid_txt;
    private javax.swing.JTextField uid_TF;
    private javax.swing.JButton viewdetail_btn;
    // End of variables declaration//GEN-END:variables

}
